### ISSUE TITLE
Docs: setup HW entropy for TLS

### ISSUE THREAD

**Issue by npeditto** [crossbario/autobahn-python#1086]
Sometimes at boot time happens this error in connection to crossbar (wss://). But after boot if I try to restart my service, it works fine.

Autobahn v18.10.1
Python 3.5.3

```
2018-11-22 16:10:41.398 474 INFO autobahn.asyncio.component.Component [-] connecting once using transport type "websocket" over endpoint "tcp"
2018-11-22 16:10:41.408 474 ERROR asyncio [-] Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x755234f0>
transport: <_SelectorSocketTransport closing fd=8 read=idle write=<idle, bufsize=0>>: ssl.SSLError: getrandom() initialization failed. (_ssl.c:720)
2018-11-22 16:10:41.408 474 ERROR asyncio Traceback (most recent call last):
2018-11-22 16:10:41.408 474 ERROR asyncio   File "/usr/lib/python3.5/asyncio/sslproto.py", line 635, in _process_write_backlog
2018-11-22 16:10:41.408 474 ERROR asyncio     self._on_handshake_complete)
2018-11-22 16:10:41.408 474 ERROR asyncio   File "/usr/lib/python3.5/asyncio/sslproto.py", line 135, in do_handshake
2018-11-22 16:10:41.408 474 ERROR asyncio     ssldata, appdata = self.feed_ssldata(b'', only_handshake=True)
2018-11-22 16:10:41.408 474 ERROR asyncio   File "/usr/lib/python3.5/asyncio/sslproto.py", line 201, in feed_ssldata
2018-11-22 16:10:41.408 474 ERROR asyncio     self._sslobj.do_handshake()
2018-11-22 16:10:41.408 474 ERROR asyncio   File "/usr/lib/python3.5/ssl.py", line 641, in do_handshake
2018-11-22 16:10:41.408 474 ERROR asyncio     self._sslobj.do_handshake()
2018-11-22 16:10:41.408 474 ERROR asyncio ssl.SSLError: getrandom() initialization failed. (_ssl.c:720)
2018-11-22 16:10:41.408 474 ERROR asyncio
2018-11-22 16:10:41.418 474 INFO autobahn.asyncio.component.Component [-] Connection failed: SSLError: getrandom() initialization failed. (_ssl.c:720)
```

Any suggestion?

**Comment by oberstet** [comment]
yeah, insufficient entropy seems like a plausible explanation. I have never seen it myself before, but there is some stuff on the web, eg https://stackoverflow.com/a/50590564/884770

could you try `sudo apt install rng-tools` and see if that ends the intermittent failures?

also (no clue what's needed here to actually use the HW):

```
(cpy371_1) oberstet@thinkpad-x1:~/scm/xbr/xbr-protocol$ cat /etc/default/rng-tools
# Configuration for the rng-tools initscript
# $Id: rng-tools.default,v 1.1.2.5 2008-06-10 19:51:37 hmh Exp $

# This is a POSIX shell fragment

# Set to the input source for random data, leave undefined
# for the initscript to attempt auto-detection.  Set to /dev/null
# for the viapadlock and tpm drivers.
#HRNGDEVICE=/dev/hwrng
#HRNGDEVICE=/dev/null

# Additional options to send to rngd. See the rngd(8) manpage for
# more information.  Do not specify -r/--rng-device here, use
# HRNGDEVICE for that instead.
#RNGDOPTIONS="--hrng=intelfwh --fill-watermark=90% --feed-interval=1"
#RNGDOPTIONS="--hrng=viakernel --fill-watermark=90% --feed-interval=1"
#RNGDOPTIONS="--hrng=viapadlock --fill-watermark=90% --feed-interval=1"
#RNGDOPTIONS="--hrng=tpm --fill-watermark=90% --feed-interval=1"
```
https://www.howtoforge.com/helping-the-random-number-generator-to-gain-enough-entropy-with-rng-tools-debian-lenny

**Comment by npeditto** [comment]
> `Component` try to re-connect after this happens

Actually I noticed that happens at each reboot.

The HW is a raspberry pi 3 module.

As you suggest I will try to install/configure rng-tools and I will let you know. THX

**Comment by oberstet** [comment]
just tested on a current intel cpu, using `rngtest -c 100000 < /dev/random` shows the HW rnd is actually used:

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     ZEIT+ BEFEHL                                                                                                                                                                                                          
16063 root      20   0    9916    128      0 R  87,4  0,0   1:05.78 rngd                                                                                                                                                                                                            
16303 oberstet  20   0    4520    784    720 S  46,5  0,0   0:20.49 rngtest         
```

with `rngtest -c 100000 < /dev/urandom`, the HW rng seems only be used for seeding.

```
(cpy371_1) oberstet@thinkpad-x1:~/scm/xbr/xbr-protocol$ rngtest -c 100000 < /dev/urandom
rngtest 5
Copyright (c) 2004 by Henrique de Moraes Holschuh
This is free software; see the source for copying conditions.  There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

rngtest: starting FIPS tests...
rngtest: bits received from input: 2000000032
rngtest: FIPS 140-2 successes: 99919
rngtest: FIPS 140-2 failures: 81
rngtest: FIPS 140-2(2001-10-10) Monobit: 16
rngtest: FIPS 140-2(2001-10-10) Poker: 6
rngtest: FIPS 140-2(2001-10-10) Runs: 37
rngtest: FIPS 140-2(2001-10-10) Long run: 23
rngtest: FIPS 140-2(2001-10-10) Continuous run: 0
rngtest: input channel speed: (min=241.437; avg=1291.197; max=1733.953)Mibits/s
rngtest: FIPS tests speed: (min=17.245; avg=100.947; max=111.541)Mibits/s
rngtest: Program run time: 20380721 microseconds
(cpy371_1) oberstet@thinkpad-x1:~/scm/xbr/xbr-protocol$ rngtest -c 100000 < /dev/random
rngtest 5
Copyright (c) 2004 by Henrique de Moraes Holschuh
This is free software; see the source for copying conditions.  There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

rngtest: starting FIPS tests...
rngtest: bits received from input: 2000000032
rngtest: FIPS 140-2 successes: 99913
rngtest: FIPS 140-2 failures: 87
rngtest: FIPS 140-2(2001-10-10) Monobit: 8
rngtest: FIPS 140-2(2001-10-10) Poker: 12
rngtest: FIPS 140-2(2001-10-10) Runs: 33
rngtest: FIPS 140-2(2001-10-10) Long run: 35
rngtest: FIPS 140-2(2001-10-10) Continuous run: 0
rngtest: input channel speed: (min=1.264; avg=6.875; max=9.300)Mibits/s
rngtest: FIPS tests speed: (min=11.973; avg=90.071; max=110.251)Mibits/s
rngtest: Program run time: 298647882 microseconds
```

**Comment by npeditto** [comment]
I installed that tool
`sudo apt install rng-tools`

then un-comment this line in /etc/default/rng-tools conf file:
`HRNGDEVICE=/dev/hwrng`

and enable/start the service:
`systemctl enable rng-tools

systemctl start rng-tools
`
The system properly booted many times so for me the problem is solved! Thanks guys for the support!

**Comment by oberstet** [comment]
thanks for reporting back! we'll add it to the docs (hence I reopen this issue)

**Comment by ofekp** [comment]
For me, simply installing `rng-tools` resolved the issue.
`sudo apt install rng-tools`
