### ISSUE TITLE
Calling "wamp.session.get" cause "WAMP message serialization error"

### ISSUE THREAD

**Issue by goldcode88** [crossbario/autobahn-python#1096]
Crossbar version: v18.11.1
Python version: 3.4
OS version: Centos 7

autobahn.js code:
```
    session.call("wamp.session.get", [details.caller]).then(
        res =>  {
            console.log("res:", res);
        },
        err => {
            console.log("err:", err);
        });
```

It will always cause crossbar error. It's a reproducible error.
```
2018-12-22T03:39:46+0000 [Router       2491] WAMP message serialization error: <autobahn.wamp.types.SessionDetails object at 0x7fcb60217750> is not JSON serializable
2018-12-22T03:39:46+0000 [Router       2491] INTERNAL ERROR in router incoming message processing
2018-12-22T03:39:46+0000 [Router       2491] 
Traceback (most recent call last):
  File "/root/penv/lib/python3.4/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
    self._runCallbacks()
  File "/root/penv/lib/python3.4/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/penv/lib/python3.4/site-packages/autobahn/wamp/protocol.py", line 971, in success
    self._transport.send(reply)
  File "/root/penv/lib/python3.4/site-packages/crossbar/router/session.py", line 213, in send
    self._router.process(self._session, msg)
--- <exception caught here> ---
  File "/root/penv/lib/python3.4/site-packages/crossbar/router/router.py", line 284, in process
    self._dealer.processYield(session, msg)
  File "/root/penv/lib/python3.4/site-packages/crossbar/router/dealer.py", line 1133, in processYield
    self._router.send(invocation_request.caller, reply)
  File "/root/penv/lib/python3.4/site-packages/crossbar/router/router.py", line 240, in send
    session._transport.send(msg)
  File "/root/penv/lib/python3.4/site-packages/autobahn/wamp/websocket.py", line 123, in send
    raise SerializationError(u"WAMP message serialization error: {0}".format(e))
autobahn.wamp.exception.SerializationError: WAMP message serialization error: <autobahn.wamp.types.SessionDetails object at 0x7fcb60217750> is not JSON serializable
```

**Comment by oddjobz** [comment]
@goldcode88 Hi, could you just confirm whether you are using Crossbar built from source or using a Crossbar FX EXE? This seems to be a match for issue #165 filed against CrossbarFX on the 18th of November.

**Comment by meejah** [comment]
actually a crossbar bug, see https://github.com/crossbario/crossbar/pull/1452
