### ISSUE TITLE
keyword arguments don't work in python 2.7

### ISSUE THREAD

**Issue by dionytadema** [crossbario/autobahn-python#1108]
running the complex rpc example in python 2.7 with autobahn 19.1.1 doesn't work.

it seems like autobahn fails to convert the keyword arg keys to unicode:

```
2019-02-08T12:04:29+0100 session attached
2019-02-08T12:04:29+0100 procedures registered
2019-02-08T12:04:33+0100 Unhandled error in Deferred:
2019-02-08T12:04:33+0100 Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/autobahn/wamp/websocket.py", line 95, in onMessage
    self._session.onMessage(msg)
  File "/usr/local/lib/python2.7/dist-packages/autobahn/wamp/protocol.py", line 1012, in onMessage
    txaio.add_callbacks(on_reply, success, error)
  File "/usr/local/lib/python2.7/dist-packages/txaio/tx.py", line 506, in add_callbacks
    future.addCallbacks(callback, errback)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 310, in addCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/autobahn/wamp/protocol.py", line 965, in success
    kwargs=res.kwresults)
  File "/usr/local/lib/python2.7/dist-packages/autobahn/wamp/message.py", line 4471, in __init__
    self.kwargs = _validate_kwargs(kwargs)
  File "/usr/local/lib/python2.7/dist-packages/autobahn/wamp/message.py", line 318, in _validate_kwargs
    raise ProtocolError(u"{0}: invalid type {1} for key in WAMP kwargs ('{2}')".format(message, type(k), k))
autobahn.wamp.exception.ProtocolError: WAMP message invalid: invalid type <type 'str'> for key in WAMP kwargs ('ci')
```

am i doing something wrong or is this actually broken? as i assume that the example should run

**Comment by om26er** [comment]
Just to be sure, you are talking about this example https://github.com/crossbario/autobahn-python/tree/master/examples/twisted/wamp/pubsub/complex ?

If so, I just tried it with Python 2 and it ran fine for me. Could you please update Crossbar to the latest version ?

**Comment by dionytadema** [comment]
no i was talking about the complex rpc example, https://github.com/crossbario/autobahn-python/blob/master/examples/twisted/wamp/rpc/complex
 i ran it again on version 19.0.0 and it still crashes

**Comment by oberstet** [comment]
autobahn python runs on py2. you can check out our test reports for py2.7 here https://travis-ci.org/crossbario/autobahn-python/builds/496913026
