### ISSUE TITLE
Auto reconnection stop after "skipping opening handshake timeout: WebSocket connection is already closed"

### ISSUE THREAD

**Issue by npeditto** [crossbario/autobahn-python#1153]
Hi,
in my application with (autobahn v19.3.3: but I noticed the same "issue" also in v18.10.1 and I don't know in the others) I notice that the auto-reconnection procedures stop working after these events, in particular after

```
2019-03-25 15:30:08.191 13776 DEBUG autobahn.asyncio.websocket.WebSocketClientProtocol [-] _connectionLost: [Errno 104] Connection reset by peer _log /usr/local/lib/python3.5/dist-packages/txaio/aio.py:201
2019-03-25 15:30:12.311 13776 DEBUG autobahn.asyncio.websocket.WebSocketClientProtocol [-] skipping opening handshake timeout: WebSocket connection is already closed _log /usr/local/lib/python3.5/dist-packages/txaio/aio.py:201
```

Is it normal? is there a solution to continue/start the reconnection procedures?

Crossbar v18.9.2

Full report logs:
```
2019-03-25 15:29:00.597 13776 DEBUG autobahn.asyncio.component.Component [-] component failed: TransportLost: failed to complete connection _log /usr/local/lib/python3.5/dist-packages/txaio/aio.py:201
2019-03-25 15:29:00.609 13776 DEBUG autobahn.asyncio.component.Component [-] Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/txaio/aio.py", line 514, in done
    res = f.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/local/lib/python3.5/dist-packages/txaio/aio.py", line 514, in done
    res = f.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
autobahn.wamp.exception.TransportLost: failed to complete connection
 _log /usr/local/lib/python3.5/dist-packages/txaio/aio.py:201
2019-03-25 15:29:00.615 13776 ERROR autobahn.asyncio.component.Component [-] Connection failed: TransportLost: failed to complete connection: autobahn.wamp.exception.TransportLost: failed to complete connection
2019-03-25 15:29:00.624 13776 DEBUG autobahn.asyncio.component.Component [-] Entering re-connect loop _log /usr/local/lib/python3.5/dist-packages/txaio/aio.py:201
2019-03-25 15:29:00.631 13776 DEBUG autobahn.asyncio.component.Component [-] trying transport 0 using connect delay 25.279705208019543 _log /usr/local/lib/python3.5/dist-packages/txaio/aio.py:201
2019-03-25 15:29:25.946 13776 INFO autobahn.asyncio.component.Component [-] connecting once using transport type "websocket" over endpoint "tcp"
2019-03-25 15:29:29.403 13776 DEBUG autobahn.asyncio.component.Component [-] component failed: ConnectionResetError: [Errno 104] Connection reset by peer _log /usr/local/lib/python3.5/dist-packages/txaio/aio.py:201
2019-03-25 15:29:29.448 13776 DEBUG autobahn.asyncio.component.Component [-] Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/txaio/aio.py", line 514, in done
    res = f.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/local/lib/python3.5/dist-packages/txaio/aio.py", line 514, in done
    res = f.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/local/lib/python3.5/dist-packages/txaio/aio.py", line 514, in done
    res = f.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/local/lib/python3.5/dist-packages/txaio/aio.py", line 514, in done
    res = f.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/local/lib/python3.5/dist-packages/txaio/aio.py", line 514, in done
    res = f.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 400, in wait_for
    return fut.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 801, in create_connection
    sock, protocol_factory, ssl, server_hostname)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 827, in _create_connection_transport
    yield from waiter
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 723, in _read_ready
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer
 _log /usr/local/lib/python3.5/dist-packages/txaio/aio.py:201
2019-03-25 15:29:29.454 13776 INFO autobahn.asyncio.component.Component [-] Connection failed: ConnectionResetError: [Errno 104] Connection reset by peer
2019-03-25 15:29:29.471 13776 DEBUG autobahn.asyncio.component.Component [-] Entering re-connect loop _log /usr/local/lib/python3.5/dist-packages/txaio/aio.py:201
2019-03-25 15:29:29.480 13776 DEBUG autobahn.asyncio.component.Component [-] trying transport 0 using connect delay 34.52392114857189 _log /usr/local/lib/python3.5/dist-packages/txaio/aio.py:201
2019-03-25 15:30:04.060 13776 INFO autobahn.asyncio.component.Component [-] connecting once using transport type "websocket" over endpoint "tcp"
2019-03-25 15:30:08.150 13776 DEBUG autobahn.asyncio.websocket.WebSocketClientProtocol [-] 
[('logOctets', False, 'WampWebSocketClientFactory'),
 ('logFrames', False, 'WampWebSocketClientFactory'),
 ('trackTimings', False, 'WampWebSocketClientFactory'),
 ('utf8validateIncoming', True, 'WampWebSocketClientFactory'),
 ('applyMask', True, 'WampWebSocketClientFactory'),
 ('maxFramePayloadSize', 0, 'WampWebSocketClientFactory'),
 ('maxMessagePayloadSize', 0, 'WampWebSocketClientFactory'),
 ('autoFragmentSize', 0, 'WampWebSocketClientFactory'),
 ('failByDrop', True, 'WampWebSocketClientFactory'),
 ('echoCloseCodeReason', False, 'WampWebSocketClientFactory'),
 ('openHandshakeTimeout', 5, 'WampWebSocketClientFactory'),
 ('closeHandshakeTimeout', 1, 'WampWebSocketClientFactory'),
 ('tcpNoDelay', True, 'WampWebSocketClientFactory'),
 ('autoPingInterval', 0, 'WampWebSocketClientFactory'),
 ('autoPingTimeout', 0, 'WampWebSocketClientFactory'),
 ('autoPingSize', 4, 'WampWebSocketClientFactory'),
 ('version', 18, 'WampWebSocketClientFactory'),
 ('acceptMaskedServerFrames', False, 'WampWebSocketClientFactory'),
 ('maskClientFrames', True, 'WampWebSocketClientFactory'),
 ('serverConnectionDropTimeout', 1, 'WampWebSocketClientFactory'),
 ('perMessageCompressionOffers', [], 'WampWebSocketClientFactory'),
 ('perMessageCompressionAccept',
  <function WebSocketClientFactory.resetProtocolOptions.<locals>.<lambda> at 0xb3d51300>,
  'WampWebSocketClientFactory')] _log /usr/local/lib/python3.5/dist-packages/txaio/aio.py:201
2019-03-25 15:30:08.163 13776 DEBUG autobahn.asyncio.websocket.WebSocketClientProtocol [-] connection to tcp:51.75.29.206:8181 established _log /usr/local/lib/python3.5/dist-packages/txaio/aio.py:201
2019-03-25 15:30:08.180 13776 DEBUG autobahn.asyncio.websocket.WebSocketClientProtocol [-] GET / HTTP/1.1
User-Agent: AutobahnPython/19.3.3
Host: <OUR-CROSSBAR-SERVER-IP>:8181
Upgrade: WebSocket
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
Sec-WebSocket-Key: 8eiSBL+/0+X97Hz9R5+JhQ==
Sec-WebSocket-Protocol: wamp.2.json
Sec-WebSocket-Version: 13

 _log /usr/local/lib/python3.5/dist-packages/txaio/aio.py:201
2019-03-25 15:30:08.191 13776 DEBUG autobahn.asyncio.websocket.WebSocketClientProtocol [-] _connectionLost: [Errno 104] Connection reset by peer _log /usr/local/lib/python3.5/dist-packages/txaio/aio.py:201
2019-03-25 15:30:12.311 13776 DEBUG autobahn.asyncio.websocket.WebSocketClientProtocol [-] skipping opening handshake timeout: WebSocket connection is already closed _log /usr/local/lib/python3.5/dist-packages/txaio/aio.py:201
```

**Comment by meejah** [comment]
Re-connection will give up on a transport if it deems an error to be "fatal". By default, nothing should be considered "fatal". (You can pass in an `is_fatal` predicate to Component).

So, I think this is a bug because it shouldn't ever stop re-connecting if you didn't pass in such a predicate.

**Comment by npeditto** [comment]
Could you suggest me (if it is possible) where I can add some logs to debug it? 

At the moment I see that the execution ends in this [function](https://github.com/crossbario/autobahn-python/blob/e883eee48a5d796e22e86a43b5f4e43e419f6d9c/autobahn/websocket/protocol.py#L788)

in particular in this "elsif":
```
        elif self.state == WebSocketProtocol.STATE_CLOSED:
            self.log.debug("skipping opening handshake timeout: WebSocket connection is already closed")
```

do you think I can modify these parameters/methods?
```
            self.wasClean = False

            self.wasOpenHandshakeTimeout = True
            self.dropConnection(abort=True)
```

**Comment by npeditto** [comment]
I closed this issue accidentally

**Comment by sergiotomasello** [comment]
Hi everybody, any news on that issue ??
thank you!

**Comment by npeditto** [comment]
The same with autobahn v19.3.3

```
2019-04-29 15:10:36.880 504 DEBUG autobahn.asyncio.component.Component [-] component failed: TransportLost: failed to complete connection _log /usr/local/lib/python3.5/dist-packages/txaio/aio.py:201
2019-04-29 15:10:36.907 504 DEBUG autobahn.asyncio.component.Component [-] Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/txaio/aio.py", line 514, in done
    res = f.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/local/lib/python3.5/dist-packages/txaio/aio.py", line 514, in done
    res = f.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
autobahn.wamp.exception.TransportLost: failed to complete connection
 _log /usr/local/lib/python3.5/dist-packages/txaio/aio.py:201
2019-04-29 15:10:36.914 504 ERROR autobahn.asyncio.component.Component [-] Connection failed: TransportLost: failed to complete connection: autobahn.wamp.exception.TransportLost: failed to complete connection
2019-04-29 15:10:36.923 504 DEBUG autobahn.asyncio.component.Component [-] Entering re-connect loop _log /usr/local/lib/python3.5/dist-packages/txaio/aio.py:201
2019-04-29 15:10:36.929 504 DEBUG autobahn.asyncio.component.Component [-] trying transport 0 using connect delay 2.3047467236444055 _log /usr/local/lib/python3.5/dist-packages/txaio/aio.py:201
2019-04-29 15:10:39.249 504 INFO autobahn.asyncio.component.Component [-] connecting once using transport type "websocket" over endpoint "tcp"
2019-04-29 15:10:49.292 504 DEBUG autobahn.asyncio.component.Component [-] component failed: TimeoutError:  _log /usr/local/lib/python3.5/dist-packages/txaio/aio.py:201
2019-04-29 15:10:49.307 504 DEBUG autobahn.asyncio.component.Component [-] Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/txaio/aio.py", line 514, in done
    res = f.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/local/lib/python3.5/dist-packages/txaio/aio.py", line 514, in done
    res = f.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/local/lib/python3.5/dist-packages/txaio/aio.py", line 514, in done
    res = f.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/local/lib/python3.5/dist-packages/txaio/aio.py", line 514, in done
    res = f.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/local/lib/python3.5/dist-packages/txaio/aio.py", line 514, in done
    res = f.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 404, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
 _log /usr/local/lib/python3.5/dist-packages/txaio/aio.py:201
2019-04-29 15:10:49.314 504 ERROR autobahn.asyncio.component.Component [-] Connection failed: TimeoutError: : concurrent.futures._base.TimeoutError
2019-04-29 15:10:49.321 504 DEBUG autobahn.asyncio.component.Component [-] Entering re-connect loop _log /usr/local/lib/python3.5/dist-packages/txaio/aio.py:201
2019-04-29 15:10:49.328 504 DEBUG autobahn.asyncio.component.Component [-] trying transport 0 using connect delay 3.3522951691978773 _log /usr/local/lib/python3.5/dist-packages/txaio/aio.py:201
2019-04-29 15:10:52.693 504 INFO autobahn.asyncio.component.Component [-] connecting once using transport type "websocket" over endpoint "tcp"
2019-04-29 15:11:02.723 504 DEBUG autobahn.asyncio.component.Component [-] component failed: TimeoutError:  _log /usr/local/lib/python3.5/dist-packages/txaio/aio.py:201
2019-04-29 15:11:02.738 504 DEBUG autobahn.asyncio.component.Component [-] Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/txaio/aio.py", line 514, in done
    res = f.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/local/lib/python3.5/dist-packages/txaio/aio.py", line 514, in done
    res = f.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/local/lib/python3.5/dist-packages/txaio/aio.py", line 514, in done
    res = f.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/local/lib/python3.5/dist-packages/txaio/aio.py", line 514, in done
    res = f.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/local/lib/python3.5/dist-packages/txaio/aio.py", line 514, in done
    res = f.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 404, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
 _log /usr/local/lib/python3.5/dist-packages/txaio/aio.py:201
2019-04-29 15:11:02.745 504 ERROR autobahn.asyncio.component.Component [-] Connection failed: TimeoutError: : concurrent.futures._base.TimeoutError
2019-04-29 15:11:02.752 504 DEBUG autobahn.asyncio.component.Component [-] Entering re-connect loop _log /usr/local/lib/python3.5/dist-packages/txaio/aio.py:201
2019-04-29 15:11:02.758 504 DEBUG autobahn.asyncio.component.Component [-] trying transport 0 using connect delay 5.00425919283392 _log /usr/local/lib/python3.5/dist-packages/txaio/aio.py:201
2019-04-29 15:11:07.778 504 INFO autobahn.asyncio.component.Component [-] connecting once using transport type "websocket" over endpoint "tcp"
2019-04-29 15:11:17.812 504 DEBUG autobahn.asyncio.component.Component [-] component failed: TimeoutError:  _log /usr/local/lib/python3.5/dist-packages/txaio/aio.py:201
2019-04-29 15:11:17.827 504 DEBUG autobahn.asyncio.component.Component [-] Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/txaio/aio.py", line 514, in done
    res = f.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/local/lib/python3.5/dist-packages/txaio/aio.py", line 514, in done
    res = f.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/local/lib/python3.5/dist-packages/txaio/aio.py", line 514, in done
    res = f.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/local/lib/python3.5/dist-packages/txaio/aio.py", line 514, in done
    res = f.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/local/lib/python3.5/dist-packages/txaio/aio.py", line 514, in done
    res = f.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 404, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
 _log /usr/local/lib/python3.5/dist-packages/txaio/aio.py:201
2019-04-29 15:11:17.833 504 ERROR autobahn.asyncio.component.Component [-] Connection failed: TimeoutError: : concurrent.futures._base.TimeoutError
2019-04-29 15:11:17.840 504 DEBUG autobahn.asyncio.component.Component [-] Entering re-connect loop _log /usr/local/lib/python3.5/dist-packages/txaio/aio.py:201
2019-04-29 15:11:17.846 504 DEBUG autobahn.asyncio.component.Component [-] trying transport 0 using connect delay 6.713639927253407 _log /usr/local/lib/python3.5/dist-packages/txaio/aio.py:201
2019-04-29 15:11:24.578 504 INFO autobahn.asyncio.component.Component [-] connecting once using transport type "websocket" over endpoint "tcp"
2019-04-29 15:11:28.693 504 DEBUG autobahn.asyncio.websocket.WebSocketClientProtocol [-] 
[('logOctets', False, 'WampWebSocketClientFactory'),
 ('logFrames', False, 'WampWebSocketClientFactory'),
 ('trackTimings', False, 'WampWebSocketClientFactory'),
 ('utf8validateIncoming', True, 'WampWebSocketClientFactory'),
 ('applyMask', True, 'WampWebSocketClientFactory'),
 ('maxFramePayloadSize', 0, 'WampWebSocketClientFactory'),
 ('maxMessagePayloadSize', 0, 'WampWebSocketClientFactory'),
 ('autoFragmentSize', 0, 'WampWebSocketClientFactory'),
 ('failByDrop', True, 'WampWebSocketClientFactory'),
 ('echoCloseCodeReason', False, 'WampWebSocketClientFactory'),
 ('openHandshakeTimeout', 5, 'WampWebSocketClientFactory'),
 ('closeHandshakeTimeout', 1, 'WampWebSocketClientFactory'),
 ('tcpNoDelay', True, 'WampWebSocketClientFactory'),
 ('autoPingInterval', 0, 'WampWebSocketClientFactory'),
 ('autoPingTimeout', 0, 'WampWebSocketClientFactory'),
 ('autoPingSize', 4, 'WampWebSocketClientFactory'),
 ('version', 18, 'WampWebSocketClientFactory'),
 ('acceptMaskedServerFrames', False, 'WampWebSocketClientFactory'),
 ('maskClientFrames', True, 'WampWebSocketClientFactory'),
 ('serverConnectionDropTimeout', 1, 'WampWebSocketClientFactory'),
 ('perMessageCompressionOffers', [], 'WampWebSocketClientFactory'),
 ('perMessageCompressionAccept',
  <function WebSocketClientFactory.resetProtocolOptions.<locals>.<lambda> at 0xb3d28930>,
  'WampWebSocketClientFactory')] _log /usr/local/lib/python3.5/dist-packages/txaio/aio.py:201
2019-04-29 15:11:28.700 504 DEBUG autobahn.asyncio.websocket.WebSocketClientProtocol [-] connection to tcp:51.75.29.206:8181 established _log /usr/local/lib/python3.5/dist-packages/txaio/aio.py:201
2019-04-29 15:11:28.710 504 DEBUG autobahn.asyncio.websocket.WebSocketClientProtocol [-] GET / HTTP/1.1
User-Agent: AutobahnPython/19.3.3
Host: wagent1-dev.felooca.eu:8181
Upgrade: WebSocket
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
Sec-WebSocket-Key: I/AoADu+mJeAYONNeO67Vw==
Sec-WebSocket-Protocol: wamp.2.json
Sec-WebSocket-Version: 13

 _log /usr/local/lib/python3.5/dist-packages/txaio/aio.py:201
2019-04-29 15:11:28.720 504 DEBUG autobahn.asyncio.websocket.WebSocketClientProtocol [-] _connectionLost: [Errno 104] Connection reset by peer _log /usr/local/lib/python3.5/dist-packages/txaio/aio.py:201
2019-04-29 15:11:33.636 504 DEBUG autobahn.asyncio.websocket.WebSocketClientProtocol [-] skipping opening handshake timeout: WebSocket connection is already closed _log /usr/local/lib/python3.5/dist-packages/txaio/aio.py:201
```

**Comment by npeditto** [comment]
The same with autobahn v19.5.1:

```
2019-06-10 10:55:37.788 1111 INFO autobahn.asyncio.component.Component [-] session leaving 'wamp.close.transport_lost'

2019-06-10 10:55:37.792 1111 WARNING [-] WAMP Session Left: reason = wamp.close.transport_lost
2019-06-10 10:55:37.794 1111 WARNING [-] WAMP Transport Left: was_clean = False

2019-06-10 10:55:37.798 1111 ERROR autobahn.asyncio.component.Component [-] Connection failed: TransportLost: failed to complete connection: autobahn.wamp.exception.TransportLost: failed to complete connection
```
after that message the reconnection procedures did not started.

**Comment by oberstet** [comment]
so the issue you see is for:

* cpython 3.5
* asyncio
* component API

need to investigate .. @meejah ?

**Comment by meejah** [comment]
I'm trying to repeat this, but am not able to -- does anyone have a way to make this happen?

**Comment by meejah** [comment]
Hmm, okay I think I've repeated it and it is indeed a asyncio-only weirdness; at this point I can see that any handshake timeout has different behavior which results in the "connect attempt failed" callbacks NOT running under asyncio (very similar code under Twisted does run). So, definitely a bug -- but seem more lower-level than the `Component` machinery.

**Comment by meejah** [comment]
(Aside: you can set client-side handshake timeouts to "very low values", which is useful in this case ;) but maybe should produce a warning if the timeout is under a second).

**Comment by meejah** [comment]
Hrrrrmmmm. Okay, so here's a thing that asyncio does: https://gist.github.com/meejah/57e5120a75fa5e8b036ff4045c3e0e53

**Comment by meejah** [comment]
https://github.com/crossbario/autobahn-python/pull/1215 should fix this

**Comment by oberstet** [comment]
@npeditto so this should be fixed via above. would be great if you could give it a try on your side .. hope it works for your case;)

**Comment by npeditto** [comment]
@oberstet and @meejah thank you guys I will let you know soon

PS when will be released a new version of autobahn?

**Comment by oberstet** [comment]
re: release: if you can confirm this really solves the issue for you, and you need it quickly, we can certainly publish a release. otherwise: "soon again";) as in a couple of weeks usually ..

**Comment by meejah** [comment]
Also "for the record" the way I was testing this was to give the client-side a very short opening handshake timeout. Less than one second "always fails" for my local tests, and 1 second "sometimes worked" locally.

```
"options": {
    "openHandshakeTimeout": 0.1
}
```

Note, as a consequence I think there are other cases where the "correct error-reason string from `onClose`" will be propagated too. Yay :)

**Comment by oberstet** [comment]
> the way I was testing this was to give the client-side a very short opening handshake timeout.

clever! yeah, I can see how that will fail with sufficiently small timeout .. though 1s or even a couple of 10ms should actually work locally .. but anyways, cool testing trick;)

**Comment by npeditto** [comment]
During these days we noticed a great improvement in wamp connection stability. So for me, if you agree, you can publish a new release or let me know when it will be possible. Thank you guys!
