### ISSUE TITLE
Process object has no attribute getPeer

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-python#1177]
there is some fallout from (I think) https://github.com/crossbario/autobahn-python/pull/1170

```
(cpy372_5) oberstet@intel-nuci7:~/scm/crossbario/project-continental-cloud/conti-rws/teststack$ make run_crossbarfx_master
crossbarfx master start --cbdir=/home/oberstet/scm/crossbario/project-continental-cloud/conti-rws/teststack/cfxmaster/.crossbar --config=config-dev.json --loglevel=info

2019-04-19T10:56:52+0200 [Controller  14548] 
2019-04-19T10:56:52+0200 [Controller  14548]     :::::::::::::::::
2019-04-19T10:56:52+0200 [Controller  14548]           :::::          _____                 __              _____  _______
2019-04-19T10:56:52+0200 [Controller  14548]     :::::   :   :::::   / ___/______  ___ ___ / /  ___ _____  / __/ |/_/ ___/
2019-04-19T10:56:52+0200 [Controller  14548]     :::::::   :::::::  / /__/ __/ _ \(_-<(_-</ _ \/ _ `/ __/ / _/_>  </ /__
2019-04-19T10:56:52+0200 [Controller  14548]     :::::   :   :::::  \___/_/  \___/___/___/_.__/\_,_/_/   /_/ /_/|_|\___/
2019-04-19T10:56:52+0200 [Controller  14548]           :::::
2019-04-19T10:56:52+0200 [Controller  14548]     :::::::::::::::::   Crossbar.io Fabric XBR Center v19.4.1 [00000]
2019-04-19T10:56:52+0200 [Controller  14548] 
2019-04-19T10:56:52+0200 [Controller  14548]     Copyright (c) 2013-2019 Crossbar.io Technologies GmbH. All rights reserved.
2019-04-19T10:56:52+0200 [Controller  14548] 
2019-04-19T10:56:52+0200 [Controller  14548] Initializing <crossbarfx.master.node.node.FabricCenterNode> as node [realm=crossbar, cbdir=/home/oberstet/scm/crossbario/project-continental-cloud/conti-rws/teststack/cfxmaster/.crossbar]
2019-04-19T10:56:52+0200 [Controller  14548] Node key files exist and are valid. Node public key is 0x7d611ed0dbcd097f51bd75ff2ce89b50a083812a787d010e0abc16dbb71ef647
2019-04-19T10:56:52+0200 [Controller  14548] Node key loaded from /home/oberstet/scm/crossbario/project-continental-cloud/conti-rws/teststack/cfxmaster/.crossbar/key.priv
2019-04-19T10:56:52+0200 [Controller  14548] Expanding built-in node configuration from local file /home/oberstet/scm/crossbario/project-continental-cloud/conti-rws/teststack/cfxmaster/.crossbar/config-dev.json
2019-04-19T10:56:52+0200 [Controller  14548] FIXME: implementation missing crossbarfx.master.personality.check_controller
2019-04-19T10:56:52+0200 [Controller  14548] Node configuration loaded [config_source=localfile, config_path=/home/oberstet/scm/crossbario/project-continental-cloud/conti-rws/teststack/cfxmaster/.crossbar/config-dev.json]
2019-04-19T10:56:52+0200 [Controller  14548] Entering event reactor ...
2019-04-19T10:56:52+0200 [Controller  14548] Starting master-node <crossbarfx.master.node.node.FabricCenterNode.start>
2019-04-19T10:56:52+0200 [Controller  14548] Starting master node <crossbar.node.node.Node.start>
2019-04-19T10:56:52+0200 [Controller  14548] Node ID cfc1 set from explicit configuration
2019-04-19T10:56:52+0200 [Controller  14548] RouterServiceAgent ready (realm_name="crossbar", on_ready=None)
2019-04-19T10:56:52+0200 [Controller  14548] Docker daemon integration disabled
2019-04-19T10:56:52+0200 [Controller  14548] Registered 48 procedures
2019-04-19T10:56:52+0200 [Controller  14548] Signal handler installed on process 14548 thread 139698221564032
2019-04-19T10:56:52+0200 [Controller  14548] Booting node <crossbarfx.master.node.node.FabricCenterNode.boot>
2019-04-19T10:56:52+0200 [Controller  14548] Booting node from local configuration [parallel_worker_start=False] .. <crossbar.node.node.Node.boot_from_config>
2019-04-19T10:56:52+0200 [Controller  14548] Will start 2 workers ..
2019-04-19T10:56:52+0200 [Controller  14548] Order node to start Router cfrouter1
2019-04-19T10:56:52+0200 [Controller  14548] Starting router worker cfrouter1 <crossbar.node.controller.NodeController.start_worker>
2019-04-19T10:56:52+0200 [Controller  14548] Unhandled Error
Traceback (most recent call last):
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/node/controller.py", line 356, in start_worker
    return self._start_native_worker(worker_type, worker_id, worker_options, details=details)
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/node/controller.py", line 695, in _start_native_worker
    d = ep.connect(transport_factory)
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/common/twisted/processutil.py", line 117, in connect
    self._childFDs)
  File "/home/oberstet/cpy372_5/lib/python3.7/site-packages/twisted/internet/posixbase.py", line 340, in spawnProcess
    processProtocol, uid, gid, childFDs)
--- <exception caught here> ---
  File "/home/oberstet/cpy372_5/lib/python3.7/site-packages/twisted/internet/process.py", line 770, in __init__
    self.proto.makeConnection(self)
  File "/home/oberstet/cpy372_5/lib/python3.7/site-packages/twisted/internet/endpoints.py", line 352, in makeConnection
    return self.protocol.makeConnection(self.transport)
  File "/home/oberstet/cpy372_5/lib/python3.7/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
    self.connectionMade()
  File "/home/oberstet/scm/crossbario/crossbar/crossbar/node/native.py", line 49, in connectionMade
    WampWebSocketClientProtocol.connectionMade(self)
  File "/home/oberstet/scm/crossbario/autobahn-python/autobahn/twisted/websocket.py", line 97, in connectionMade
    self._connectionMade()
  File "/home/oberstet/scm/crossbario/autobahn-python/autobahn/websocket/protocol.py", line 3374, in _connectionMade
    self.startHandshake()
  File "/home/oberstet/scm/crossbario/autobahn-python/autobahn/websocket/protocol.py", line 3492, in startHandshake
    transport_details = self._create_transport_details()
  File "/home/oberstet/scm/crossbario/autobahn-python/autobahn/twisted/websocket.py", line 248, in _create_transport_details
    peer=peer2str(self.transport.getPeer()),
  File "/home/oberstet/cpy372_5/lib/python3.7/site-packages/twisted/python/components.py", line 407, in __get__
    return getattr(original, self.attributeName)
builtins.AttributeError: 'Process' object has no attribute 'getPeer'
```

**Comment by oberstet** [comment]
actually, what I was afraid of;) the unit tests for the new `onConnecting` are only covering IP based transports .. not UDS and Pipes ..

**Comment by oberstet** [comment]
the fix should do the same as we had already:

```
        # the peer we are connected to
        try:
            self.peer = peer2str(self.transport.getPeer())
        except AttributeError:
            # ProcessProtocols lack getPeer()
            self.peer = u'process:{}'.format(self.transport.pid)
```

**Comment by oberstet** [comment]
ok, as I want to move on, fix is coming via https://github.com/crossbario/autobahn-python/pull/1178
