### ISSUE TITLE
Traceback on WebSocket resource status page

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-python#1218]
When using a Web transport with a WebSocket resource on a path, and when entering that full WebSocket URL (using scheme http instead of ws) in a browser address bar, Crossbar.io can render a status page - and this is broken currently:

```
Jul 03 14:39:28 <redacted> unbuffer[2114]: Traceback (most recent call last):
Jul 03 14:39:28 <redacted> unbuffer[2114]:   File "/home/ubuntu/cpy373_1/lib/python3.7/site-packages/twisted/web/_http2.py", line 186, in dataReceived
Jul 03 14:39:28 <redacted> unbuffer[2114]:     self._requestEnded(event)
Jul 03 14:39:28 <redacted> unbuffer[2114]:   File "/home/ubuntu/cpy373_1/lib/python3.7/site-packages/twisted/web/_http2.py", line 495, in _requestEnded
Jul 03 14:39:28 <redacted> unbuffer[2114]:     stream.requestComplete()
Jul 03 14:39:28 <redacted> unbuffer[2114]:   File "/home/ubuntu/cpy373_1/lib/python3.7/site-packages/twisted/web/_http2.py", line 992, in requestComplete
Jul 03 14:39:28 <redacted> unbuffer[2114]:     self._request.requestReceived(self.command, self.path, b'HTTP/2')
Jul 03 14:39:28 <redacted> unbuffer[2114]:   File "/home/ubuntu/cpy373_1/lib/python3.7/site-packages/twisted/web/http.py", line 920, in requestReceived
Jul 03 14:39:28 <redacted> unbuffer[2114]:     self.process()
Jul 03 14:39:28 <redacted> unbuffer[2114]: --- <exception caught here> ---
Jul 03 14:39:28 <redacted> unbuffer[2114]:   File "/home/ubuntu/cpy373_1/lib/python3.7/site-packages/twisted/web/server.py", line 199, in process
Jul 03 14:39:28 <redacted> unbuffer[2114]:     self.render(resrc)
Jul 03 14:39:28 <redacted> unbuffer[2114]:   File "/home/ubuntu/cpy373_1/lib/python3.7/site-packages/twisted/web/server.py", line 259, in render
Jul 03 14:39:28 <redacted> unbuffer[2114]:     body = resrc.render(self)
Jul 03 14:39:28 <redacted> unbuffer[2114]:   File "/home/ubuntu/scm/crossbario/autobahn-python/autobahn/twisted/resource.py", line 121, in render
Jul 03 14:39:28 <redacted> unbuffer[2114]:     protocol = self._factory.buildProtocol(request.transport.getPeer())
Jul 03 14:39:28 <redacted> unbuffer[2114]: builtins.AttributeError: 'NoneType' object has no attribute 'getPeer'
```

**Comment by meejah** [comment]
From the traceback, it looks like http2 was used .. so must be via TLS, right?

**Comment by oberstet** [comment]
ah yes, I think I ran into above on the c*** teststack .. which runs on TLS ..

**Comment by meejah** [comment]
I have repeated it, and have an approximate fix .. but also there's something possibly more complex going on that I don't understand, because when Twisted times out the connection there's a Twisted-code-only stacktrace too as it shuts down the connection.

```
  File "[redacted]/venv/lib/python3.6/site-packages/twisted/internet/task.py", line 936, in react
    _reactor.run()
  File "[redacted]/venv/lib/python3.6/site-packages/twisted/internet/base.py", line 1272, in run
    self.mainLoop()
  File "[redacted]/venv/lib/python3.6/site-packages/twisted/internet/base.py", line 1281, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "[redacted]/venv/lib/python3.6/site-packages/twisted/internet/base.py", line 902, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "[redacted]/venv/lib/python3.6/site-packages/twisted/web/http.py", line 2339, in forceAbortClient
    self.transport.abortConnection()
  File "[redacted]/venv/lib/python3.6/site-packages/twisted/protocols/tls.py", line 435, in abortConnection
    self._shutdownTLS()
  File "[redacted]/venv/lib/python3.6/site-packages/twisted/protocols/tls.py", line 338, in _shutdownTLS
    shutdownSuccess = self._tlsConnection.shutdown()
builtins.AttributeError: 'NoneType' object has no attribute 'shutdown'
```

**Comment by oberstet** [comment]
^ interesting;) I haven't run into this before .. dunno ..
