### ISSUE TITLE
Installing autobahn[xbr] fails

### ISSUE THREAD

**Issue by rndwb** [crossbario/autobahn-python#1230]
https://github.com/crossbario/autobahn-python/blob/d89017e9196a6c7bac8c815d5a6037154bb10deb/setup.py#L159 seems not needed. The web3 requirement already depends on eth-abi 
For me the installation failed with `ERROR: web3 4.9.2 has requirement eth-abi<2.0.0,>=1.2.0, but you'll have eth-abi 2.0.0 which is incompatible.` because autobahn already installs the newer version.
Feels like a bug in pip...

Steps to reproduce:
```
% cat Dockerfile 
FROM python:3.7-stretch
RUN pip install git+https://github.com/crossbario/autobahn-python.git@master#egg=autobahn[xbr]

% docker build -ttest.
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM python:3.7-stretch
 ---> 8a74ebe77b0d
Step 2/2 : RUN pip install git+https://github.com/crossbario/autobahn-python.git@master#egg=autobahn[xbr]
 ---> Running in 3a75fd7be04d
Collecting autobahn[xbr] from git+https://github.com/crossbario/autobahn-python.git@master#egg=autobahn[xbr]
  Cloning https://github.com/crossbario/autobahn-python.git (to revision master) to /tmp/pip-install-fbywer73/autobahn
  Running command git clone -q https://github.com/crossbario/autobahn-python.git /tmp/pip-install-fbywer73/autobahn
Collecting six>=1.11.0 (from autobahn[xbr])
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting txaio>=18.8.1 (from autobahn[xbr])
  Downloading https://files.pythonhosted.org/packages/e9/6d/e1a6f7835cde86728e5bb1f577be9b2d7d273fdb33c286e70b087d418ded/txaio-18.8.1-py2.py3-none-any.whl
Collecting cryptography>=2.7 (from autobahn[xbr])
  Downloading https://files.pythonhosted.org/packages/97/18/c6557f63a6abde34707196fb2cad1c6dc0dbff25a200d5044922496668a4/cryptography-2.7-cp34-abi3-manylinux1_x86_64.whl (2.3MB)
Collecting cbor2>=4.1.1 (from autobahn[xbr])
  Downloading https://files.pythonhosted.org/packages/21/b4/0d4050c576476bcf3b3e18f9afb2b338325279ce0efc0ddca6557adb0e6a/cbor2-4.1.2-py2.py3-none-any.whl
Collecting zlmdb>=19.7.1 (from autobahn[xbr])
  Downloading https://files.pythonhosted.org/packages/11/6f/ade54e503a34ae4859c9a630094f6f5329cbb65ac418f586b7712e77ea08/zlmdb-19.7.1-py2.py3-none-any.whl (57kB)
Collecting twisted>=18.9.0 (from autobahn[xbr])
  Downloading https://files.pythonhosted.org/packages/79/59/035de19362320e632301ed7bbde23e4c8cd6fc5e2f1cf8d354cdba857854/Twisted-19.2.1.tar.bz2 (3.1MB)
Collecting web3>=4.8.1 (from autobahn[xbr])
  Downloading https://files.pythonhosted.org/packages/24/f5/3d6e3ac1ec98dc736084a8f821b922517d5492714889bf29460d9d97bda0/web3-4.9.2-py3-none-any.whl (124kB)
Collecting py-eth-sig-utils>=0.3.0 (from autobahn[xbr])
  Downloading https://files.pythonhosted.org/packages/46/02/8e1359ba45fb5392220839a979b2c0eaa805923c2b7a4904e74c17440ef4/py_eth_sig_utils-0.3.0-py3-none-any.whl
Collecting ethereum>=2.3.2 (from autobahn[xbr])
  Downloading https://files.pythonhosted.org/packages/ca/48/bd2484ff00fad56bfabad46af8d91f0ab4c6844e389e00b00c7609b405e0/ethereum-2.3.2.tar.gz (155kB)
Collecting eth-abi>=1.3.0 (from autobahn[xbr])
  Downloading https://files.pythonhosted.org/packages/f1/ae/ba7616550d65ef7a54a98d2f34947109740b319f79f8320bed082a985b55/eth_abi-2.0.0-py3-none-any.whl

.....

Successfully built autobahn twisted ethereum pyyaml lmdb cytoolz lru-dict future pbkdf2 pyethash pysha3 scrypt parsimonious pycparser toolz   
ERROR: web3 4.9.2 has requirement eth-abi<2.0.0,>=1.2.0, but you'll have eth-abi 2.0.0 which is incompatible.
Installing collected packages: six, txaio, asn1crypto, pycparser, cffi, cryptography, cbor2, pyyaml, pynacl, numpy, lmdb, click, zlmdb, zope.interface, constantly, incremental, attrs, Automat, idna, hyperlink, PyHamcrest, twisted, toolz, cytoolz, eth-typing, pycryptodome, eth-hash, eth-utils, rlp, hexbytes, eth-rlp, eth-keys, eth-keyfile, attrdict, eth-account, websockets, certifi, chardet, urllib3, requests, parsimonious, eth-abi, lru-dict, web3, py-eth-sig-utils, coincurve, future, pbkdf2, mypy-extensions, py-ecc, pyethash, pysha3, repoze.lru, scrypt, ethereum, autobahn
Successfully installed Automat-0.7.0 PyHamcrest-1.9.0 asn1crypto-0.24.0 attrdict-2.0.1 attrs-19.1.0 autobahn-19.7.2 cbor2-4.1.2 certifi-2019.6.16 cffi-1.12.3 chardet-3.0.4 click-7.0 coincurve-12.0.0 constantly-15.1.0 cryptography-2.7 cytoolz-0.10.0 eth-abi-2.0.0 eth-account-0.3.0 eth-hash-0.2.0 eth-keyfile-0.5.1 eth-keys-0.2.4 eth-rlp-0.1.2 eth-typing-2.1.0 eth-utils-1.6.2 ethereum-2.3.2 future-0.17.1 hexbytes-0.2.0 hyperlink-19.0.0 idna-2.8 incremental-17.5.0 lmdb-0.96 lru-dict-1.1.6 mypy-extensions-0.4.1 numpy-1.15.4 parsimonious-0.8.1 pbkdf2-1.3 py-ecc-1.7.1 py-eth-sig-utils-0.3.0 pycparser-2.19 pycryptodome-3.8.2 pyethash-0.1.27 pynacl-1.3.0 pysha3-1.0.2 pyyaml-5.1.1 repoze.lru-0.7 requests-2.22.0 rlp-1.1.0 scrypt-0.8.13 six-1.12.0 toolz-0.10.0 twisted-19.2.1 txaio-18.8.1 urllib3-1.25.3 web3-4.9.2 websockets-6.0 zlmdb-19.7.1 zope.interface-4.6.0

% docker run --rm -it test
Python 3.7.4 (default, Jul 12 2019, 01:10:03) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import web3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/web3/__init__.py", line 8, in <module>
    from web3.main import Web3  # noqa: E402
  File "/usr/local/lib/python3.7/site-packages/web3/main.py", line 16, in <module>
    from web3.eth import Eth
  File "/usr/local/lib/python3.7/site-packages/web3/eth.py", line 13, in <module>
    from web3.contract import (
  File "/usr/local/lib/python3.7/site-packages/web3/contract.py", line 33, in <module>
    from web3.utils.abi import (
  File "/usr/local/lib/python3.7/site-packages/web3/utils/abi.py", line 10, in <module>
    from eth_abi.abi import (
ImportError: cannot import name 'collapse_type' from 'eth_abi.abi' (/usr/local/lib/python3.7/site-packages/eth_abi/abi.py)
>>>
```

**Comment by oberstet** [comment]
This is fixed (for v19.11.2+): all XBR dependencies have been made optional and can be installed via `pip install autobahn[xbr]`
