### ISSUE TITLE
flaky test: test_non_depleting

### ISSUE THREAD

**Issue by om26er** [crossbario/autobahn-python#1278]
The test occasionally fails, here is one such instance https://travis-ci.org/crossbario/autobahn-python/jobs/628375836

**Comment by yan12125** [comment]
FWIW, `test_non_depleting` fails consistently on my machine. Here is a sample run: (I commented out `test_depleting` as it appears to never finish like what https://github.com/crossbario/autobahn-python/issues/1275 described)
```
$ PYTHONPATH=. trial3 autobahn/test/test_rng.py
autobahn.test.test_rng
  TestEntropy
    test_non_depleting ... 
system entropy depletion stats:
0: 1000
                                              [FAIL]

===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/home/yen/tmp/autobahn-python/autobahn/test/test_rng.py", line 87, in test_non_depleting
    self.assertTrue(skeys[0] > 10)
  File "/usr/lib/python3.8/unittest/case.py", line 765, in assertTrue
    raise self.failureException(msg)
builtins.AssertionError: False is not true

autobahn.test.test_rng.TestEntropy.test_non_depleting
-------------------------------------------------------------------------------
Ran 1 tests in 6.468s

FAILED (failures=1)
```
Tested with autobahn commit ae29569ac03c51a7a7aa106a498a903b8f457bb0.

**Comment by oberstet** [comment]
ok, pls see https://github.com/crossbario/autobahn-python/issues/1275#issuecomment-574105216

I have left the test active in our CI .. but yes, the test did fail for me in the past occasionally as well .. it is definitely somewhat non-deterministic (and hence not really correct). hence, for now, I leave this issue open ..
