### ISSUE TITLE
XBR: SimpleSeller lacks default KeySeries class

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-python#1297]
not sure where/when we lost that one .. workaround:

```
seller = SimpleSeller(self._market_maker_adr, privkey, provider_id=username_sha3)
seller.KeySeries = KeySeries
```

the error triggered looks like:

```
road_vehicle_1            | 2020-01-18T13:31:00+0000 RoadVehicle.onUserError(): "While firing onJoin"
road_vehicle_1            | Traceback (most recent call last):
road_vehicle_1            |   File "/usr/local/lib/python3.8/site-packages/autobahn/wamp/protocol.py", line 557, in <lambda>
road_vehicle_1            |     lambda _: txaio.as_future(self.onJoin, details),
road_vehicle_1            |   File "/usr/local/lib/python3.8/site-packages/txaio/tx.py", line 428, in as_future
road_vehicle_1            |     return ensureDeferred(fun(*args, **kwargs))
road_vehicle_1            |   File "/usr/local/lib/python3.8/site-packages/twisted/internet/defer.py", line 911, in ensureDeferred
road_vehicle_1            |     return _cancellableInlineCallbacks(coro)
road_vehicle_1            |   File "/usr/local/lib/python3.8/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
road_vehicle_1            |     _inlineCallbacks(None, g, status)
road_vehicle_1            | --- <exception caught here> ---
road_vehicle_1            |   File "/usr/local/lib/python3.8/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
road_vehicle_1            |     result = g.send(result)
road_vehicle_1            |   File "/app/client.py", line 71, in onJoin
road_vehicle_1            |     await self._initialize(details.authid, userdata, vehicledata, city, run_id)
road_vehicle_1            |   File "/app/client.py", line 131, in _initialize
road_vehicle_1            |     self._sellers[username] = make_seller(username)
road_vehicle_1            |   File "/app/client.py", line 125, in make_seller
road_vehicle_1            |     seller.add(api_id.bytes, prefix, price, interval, categories)
road_vehicle_1            |   File "/usr/local/lib/python3.8/site-packages/autobahn/xbr/_seller.py", line 343, in add
road_vehicle_1            |     key_series = self.KeySeries(api_id, price, interval, on_rotate)
road_vehicle_1            | builtins.TypeError: 'NoneType' object is not callable
road_vehicle_1            | 
```

**Comment by oberstet** [comment]
ah, this is invalid .. need to import the right class;)
