### ISSUE TITLE
CLI tool is broken

### ISSUE THREAD

**Issue by om26er** [crossbario/autobahn-python#1345]
This has been appearing in our CI
```
builder.wheel_pushed --keyword name txaio --keyword publish true

Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.7.1/bin/wamp", line 6, in <module>

    from autobahn.__main__ import _main

  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/autobahn/__main__.py", line 37, in <module>

    from autobahn.twisted.component import Component

  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/autobahn/twisted/__init__.py", line 36, in <module>

    from autobahn.twisted.util import sleep

  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/autobahn/twisted/util.py", line 30, in <module>

    from twisted.internet.address import IPv4Address, UNIXAddress

  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/twisted/internet/address.py", line 101, in <module>

    @attr.s(hash=False, repr=False, eq=False)

TypeError: attrs() got an unexpected keyword argument 'eq'
```

Look here for example https://travis-ci.org/github/crossbario/txaio/jobs/665077629

**Comment by om26er** [comment]
I think that was a false alarm, the actual issue is a dependency mismatch in the CI
```
automat 20.2.0 has requirement attrs>=19.2.0, but you'll have attrs 18.2.0 which is incompatible.
twisted 20.3.0 has requirement attrs>=19.2.0, but you'll have attrs 18.2.0 which is incompatible.
```

**Comment by om26er** [comment]
I believe that is not a autobahn-python bug, closing.
