### ISSUE TITLE
Document test strategies for user-level WAMP

### ISSUE THREAD

**Issue by Lois31** [crossbario/autobahn-python#1391]
I am trying to set up unit tests to validate my WAMP component.
After taking a look at the different [tests](https://github.com/crossbario/autobahn-python/blob/master/autobahn/wamp/test/test_component.py) implemented in the autobahn project, I realized that these used the twisted module.
Now that the unittest module of python natively integrates a means of testing coroutines via the unittest.IsolatedAsyncioTestCase class, since python 3.8, is it possible to provide a test of a WAMP component via the asyncio and uniittest modules ?

**Comment by Lois31** [comment]
I tried to use the _twisted.trial_ module as in your tests, however I get the following error: `builtins.RuntimeError: Explicitly using 'twisted' already`. Because I use _asyncio_ and not _twisted_ for my WAMP component.
I also tried to launch my WAMP components: _backend.py_ and _client.py_ in a separate thread with its own event loop. Unsuccessful with the following error:
```
Traceback (most recent call last):
  File "python3.8/asyncio/unix_events.py", line 95, in add_signal_handler
    signal.set_wakeup_fd(self._csock.fileno())
ValueError: set_wakeup_fd only works in main thread

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "utils.py", line 109, in run_components
    run([component.asyncio_component for component in components])
  File "python3.8/site-packages/autobahn/asyncio/component.py", line 383, in run
    loop.add_signal_handler(signal.SIGINT, lambda: asyncio.ensure_future(nicely_exit("SIGINT")))
  File "python3.8/asyncio/unix_events.py", line 97, in add_signal_handler
    raise RuntimeError(str(exc))
RuntimeError: set_wakeup_fd only works in main thread
```
Do you have any leads to test a WAMP component based on the _asyncio_ module?

**Comment by oberstet** [comment]
> I am trying to set up unit tests to validate my WAMP component.

in general, a lot will depend on what exactly your goal is.

eg if "test component" means test that a procedure provided in your component can be actually called from a different component, and that the "correct" (wrt to your app) app level return value is given back to the caller. if so, this is "functional testing", and will require a WAMP router for the tests to run. eg if "test components" means that your component can be successfully instantiated (constructed)  and only that. this is an example "unit testing".

**Comment by Lois31** [comment]
These are indeed functional tests that I am trying to set up where I wish to test each procedure call and arguments of my WAMP component asyncio.

**Comment by Lois31** [comment]
Hello,
After several unsuccessful attempts, I still cannot test my WAMP component based on the asyncio module.
Is there a way to get an instance of an ApplicationSession after calling the run() method? So that I can use it in the unittest framework.
Do you have a sample code using the asyncio module?
Thank you for your help.

**Comment by meejah** [comment]
If you're really trying to do actual local networking, you'll probably want the components running in different processes (right?). No matter that, you'll need to arrange for a router to run (e.g. crossbar) if you want to do "real WAMP network things" (and that will have to run in a separate process).

I personally like `py.test` for this kind of testing (because the "fixtures" can be shared and provide an intuitive interface). As you've discovered, you can only use *one* framework per process (that is, you can't import from `autobahn.wamp.twisted` and `autobahn.wamp.asyncio` in the same process).

If instead you really do mean to do unit-style tests, that should also be possible. Us main developers prefer Twisted and so that's a big reason that framework is used for many tests. Another reason is because `Deferred`s in Twisted **don't** need to "go through the reactor" (unlike asyncio) so it's possible to write non-network-using tests that don't need the reactor to loop arbitrary numbers of times. Perhaps this new support you mention helps here, though?

One way to proceed would be if you could write a SSCCE (http://sscce.org) of the sort of tests you'd *like* to write -- ideally this could become a "guide" / docs ultimately. If you need help while doing this, `#autobahn` in IRC or the Forum https://forum.crossbar.io/ can provide Q&A style assistance.

I don't know if asyncio provides a similar API but Twisted provides some support for in-memory "networking" for testing. A contributor added some WebSocket testing using this infrastructure; see e.g. https://github.com/crossbario/autobahn-python/blob/master/autobahn/twisted/testing/__init__.py#L278

For pure unit-tests, you can of course still just call the functions you register as subscribers or RPC endpoints.

As for your immediate request ("how to get a `Session` instance") you will receive it during the "join". So using the `Component` API, here's a way (this should work if you run the autobahn example router).

```
import txaio
import asyncio
from autobahn.asyncio.component import Component


async def some_test():
    comp = Component(
        transports="ws://localhost:8080/ws",
        realm="crossbardemo",
    )

    f = txaio.create_future()

    @comp.on_join
    def joined(session, details):
        print("the session: {}".format(session))
        txaio.resolve(f, session)

    comp.start()  # the future from this fires when the component is "done"
    session = await f
    print("have session: {}".format(session))
    answer = await session.call(u"some.rpc.endpoint", "arg", 1)


if __name__ == "__main__":
    asyncio.get_event_loop().run_until_complete(some_test())
```

**Comment by Lois31** [comment]
Hello meejah,
Below an example (not functional), of what I would like to set up.
Of course this example is very simple. But it will allow us to verify that all the languages (Python, Java, C++, Typescript) and the different COTS used (msgpack, Boost, ...) work correctly together.

**Client component**
```
import asyncio
import unittest
import txaio
from autobahn.asyncio.wamp import ApplicationSession
from autobahn.asyncio.component import Component, run

txaio.use_asyncio()
log = txaio.make_logger()
txaio.start_logging(level='info')


class Client(ApplicationSession):
    def __init__(self, config=None):
        config.realm = 'TESTS'
        super().__init__(config)

    async def onJoin(self, details):
        log.info('Info: client login !')
        loop = asyncio.get_running_loop()
        loop.create_task(self.test_echo_payload())

    async def onDisconnect(self):
        log.info(f'Info: client logout...')
        loop  = asyncio.get_event_loop()
        tasks = [task for task in asyncio.all_tasks(loop) if task is not asyncio.current_task(loop)]
        list(map(lambda task: task.cancel(), tasks))
        await asyncio.gather(*tasks, return_exceptions=True)
        log.info('Info: Finished awaiting cancelled tasks')
        loop.stop()


class TesterFixture(unittest.IsolatedAsyncioTestCase):
    async def asyncSetUp(self):
        log.info('Info: Instantiating Python tester component')
        asyncio.set_event_loop(asyncio.new_event_loop())
        # Launch the Client component
        client = Component(
            session_factory = Client,
            transports      = [
                {
                    'type':        'websocket',
                    'serializers': ['msgpack'],
                    'url':         'ws://localhost:8909/ws',
                    'max_retries': 3
                }
            ]
        )
        run([client])

    async def asyncTearDown(self):
        log.info('Info: TearDown')

    async def on_cleanup(self):
        log.info('Info: cleanup')


    ############################################################
    ## Tests
    async def test_echo_boolean(self):
        log.info('Info: test_echo_boolean')
        ret = await self.client.call_test_echo_boolean(True)
        self.assertEqual(ret, True)

    async def test_echo_payload(self):
        log.info('Info: test_echo_payload')
        payload = b'\x00\x01\x02\x03\x04\x05\x06\x07\x08\x09\x10\xF0'
        ret = await self.client.call('test.echo.payload', payload)
        self.assertEqual(ret, payload)


###############################################################################
# Main
if __name__ == '__main__':
    unittest.main()
```

**Backend component**
```
import asyncio
import txaio
from autobahn.asyncio.wamp import ApplicationSession
from autobahn.asyncio.component import Component, run

txaio.use_asyncio()
log = txaio.make_logger()
txaio.start_logging(level='info')

class Backend(ApplicationSession):
    def __init__(self, config=None):
        config.realm = 'TESTS'
        super().__init__(config)

    async def onJoin(self, details):
        log.info('Info: Backend login !')
        await self.register(self.test_echo_boolean, 'test.echo.boolean')
        await self.register(self.test_echo_payload, 'test.echo.payload')

    async def onDisconnect(self):
        log.info(f'Info: Backend logout...')
        loop  = asyncio.get_event_loop()
        tasks = [task for task in asyncio.all_tasks(loop) if task is not asyncio.current_task(loop)]
        list(map(lambda task: task.cancel(), tasks))
        await asyncio.gather(*tasks, return_exceptions=True)
        log.info('Info: Finished awaiting cancelled tasks')
        loop.stop()


    async def test_echo_boolean(self, value: bool) -> bool:
        return value

    async def test_echo_payload(self, value: bytes) -> bytes:
        return value


###############################################################################
# Main
if __name__ == '__main__':
    backend = Component(
            session_factory = Backend,
            transports      = [
                {
                    'type':        'websocket',
                    'serializers': ['msgpack'],
                    'url':         'ws://localhost:8909/ws',
                    'max_retries': 3
                }
            ]
        )

    run([backend])
```

**Crossbar WAMP router configuration**
```
{
  "$schema": "https://raw.githubusercontent.com/crossbario/crossbar/master/crossbar.json",
  "version": 2,
  "controller": {
  },
  "workers": [
    {
      "type": "router",
      "realms": [
        {
          "name": "TESTS",
          "roles": [
            {
              "name": "anonymous",
              "permissions": [
                {
                  "uri": "",
                  "match": "prefix",
                  "allow": {
                    "call": true,
                    "register": true,
                    "publish": true,
                    "subscribe": true
                  },
                  "disclose": {
                    "caller": false,
                    "publisher": false
                  },
                  "cache": true
                }
              ]
            }
          ]
        }
      ],
      "transports": [
        {
          "type": "web",
          "endpoint": {
            "type": "tcp",
            "port": 8909,
            "backlog": 1024
          },
          "paths": {
            "/": {
              "type": "static",
              "directory": "../web",
              "options": {
                "enable_directory_listing": true
              }
            },
            "ws": {
              "type": "websocket",
              "serializers": [
                "msgpack"
              ],
              "options": {
                "allowed_origins": ["*"],
                "allow_null_origin": true,
                "enable_webstatus": false,
                "max_frame_size": 1048576,
                "max_message_size": 1048576,
                "auto_fragment_size": 65536,
                "fail_by_drop": true,
                "open_handshake_timeout": 2500,
                "close_handshake_timeout": 1000,
                "auto_ping_interval": 10000,
                "auto_ping_timeout": 5000,
                "auto_ping_size": 4,
                "compression": {
                  "deflate": {
                    "request_no_context_takeover": false,
                    "request_max_window_bits": 13,
                    "no_context_takeover": false,
                    "max_window_bits": 13,
                    "memory_level": 5
                  }
                }
              }
            },
            "info": {
              "type": "nodeinfo"
            }
          }
        }
      ]
    }
  ]
}
```

**Comment by meejah** [comment]
This sort of looks like your goal is to test Crossbar / Autobahn itself? We do have automated tests that do fairly similar tests -- these are currently in a private repo but the general setup is (as hinted above) using py.test and fixtures to set up a router with several different clients etc.

The actual py.test fixtures are basically just calling out to `crossbar` (to set up the router) and using code like I posed above to start client-type sessions to the router. You could follow a similar pattern for your tests if you want to set up something similar. We don't provide helpers/infrastructure for this, but also it's fairly limited code to run a subprocess (with crossbar). The only real problem I see with your above code is that you're using the `run` helper (which won't return until the event-loop stops) so you should just use `component.start()` instead. You will also probably have an easier time if you use just one asyncio event-loop (per process).

**Comment by oberstet** [comment]
> This sort of looks like your goal is to test Crossbar / Autobahn itself? 

if that is the goal, best would be to expand our existing tests. those are twisted based (for ABPy). 

>  But it will allow us to verify that all the languages (Python, Java, C++, Typescript) and the different COTS used (msgpack, Boost, ...) work correctly together.

if the goal is cross-language integration testing, this would be a bigger undertaking. starting from how to orchestrate such tests, as there are 3 functional parts involved (at least .. but generally more): client A, router and client B.

a test could eg start:

* crossbar docker container (one node)
* client A docker container
* client B docker container

if all 3 containers are run on 1 host, all 3 could log-append to 1 file on the host. at the end of the test, after all containers have shut down, the log file could be checked against what's expected

**Comment by Lois31** [comment]
For information, following your advice, I managed to test my WAMP component with the pytest and asyncio modules:
```
# coding: utf8

###############################################################################
# import

import os
import sys
import asyncio
import pytest
import txaio
from autobahn.asyncio.wamp import ApplicationSession
from autobahn.asyncio.component import Component


###############################################################################
# Globals

txaio.use_asyncio()
log = txaio.make_logger()
txaio.start_logging()

# All test coroutines will be treated as marked.
pytestmark = pytest.mark.asyncio
future     = None


###############################################################################
# Class
class Client(ApplicationSession):
    def __init__(self, config=None):
        config.realm = 'TESTS'
        super().__init__(config)

    async def onJoin(self, details):
        global future
        #log.info('Info: client login !')
        txaio.resolve(future, self)
        ## Component Main Loop
        # log.info(f'Info: {self.get_name()} login !')

    async def onDisconnect(self):
        # log.info(f'Info: client logout...')
        loop  = asyncio.get_event_loop()
        tasks = [task for task in asyncio.all_tasks(loop) if task is not asyncio.current_task(loop)]
        list(map(lambda task: task.cancel(), tasks))
        await asyncio.gather(*tasks, return_exceptions=True)
        # log.info('Info: Finished awaiting cancelled tasks')
        loop.stop()


@pytest.fixture
async def component():
    global future

    # Launch the Client component
    client = Component(
        session_factory = Client,
        transports      = [
            {
                'type':        'websocket',
                'serializers': ['msgpack'],
                'url':         'ws://localhost:8909/ws',
                'max_retries': 3
            }
        ]
    )
    future = txaio.create_future()
    client.start(loop=asyncio.get_event_loop())
    session = await future
    return session


async def test_echo_boolean(component):
    ret = await component.call('test.echo.boolean', True)
    assert ret == True
```

However, I come across a strange error when trying to log in...
If, for example, we try to start the component as follows, **without setting the parameter _loop_**
```
client.start()
```

The following error appears:
```
============================================================================= ERRORS ==============================================================================
_______________________________________________________________ ERROR at setup of test_echo_boolean _______________________________________________________________

    @pytest.fixture
    async def component():
        global future

        # Launch the Client component
        client = Component(
            session_factory = Client,
            transports      = [
                {
                    'type':        'websocket',
                    'serializers': ['msgpack'],
                    'url':         'ws://localhost:8909/ws',
                    'max_retries': 3
                }
            ]
        )
        future = txaio.create_future()
>       client.start()

tester.py:68:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/lib/python3.8/site-packages/autobahn/asyncio/component.py:309: in start
    self.log.warn("Using default loop")
/lib/python3.8/site-packages/txaio/aio.py:162: in _log
    getattr(logger._logger, level)(msg)
/lib/python3.8/logging/__init__.py:1451: in warn
    self.warning(msg, *args, **kwargs)
/lib/python3.8/logging/__init__.py:1446: in warning
    self._log(WARNING, msg, args, **kwargs)
/lib/python3.8/logging/__init__.py:1577: in _log
    self.handle(record)
/lib/python3.8/logging/__init__.py:1587: in handle
    self.callHandlers(record)
/lib/python3.8/logging/__init__.py:1649: in callHandlers
    hdlr.handle(record)
/lib/python3.8/logging/__init__.py:950: in handle
    self.emit(record)
/lib/python3.8/site-packages/txaio/aio.py:219: in emit
    self._file.write(msg)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <_pytest.capture.EncodedFile object at 0x7fffeb6b5ca0>, s = b'2020-07-27T14:42:48 Using default loop\n'

    def write(self, s: str) -> int:
        if not isinstance(s, str):
>           raise TypeError(
                "write() argument must be str, not {}".format(type(s).__name__)
            )
E           TypeError: write() argument must be str, not bytes

/lib/python3.8/site-packages/_pytest/capture.py:421: TypeError
```

It seems that there is an incompatibility between the pytest, asyncio and txaio modules ... 
Do you have any idea?
