### ISSUE TITLE
XBR implementation expects to select a txaio framework before import

### ISSUE THREAD

**Issue by om26er** [crossbario/autobahn-python#1397]
With https://github.com/crossbario/autobahn-python/commit/3d16460ba8074a60ba2b28d05fd9c32c05481cb5, now before importing xbr, one must select a txaio framework.
```
(venv) om26er@X1C6:~/scm/crossbario/autobahn-python$ python3
Python 3.8.2 (default, Apr 27 2020, 15:53:34) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from autobahn import xbr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/om26er/scm/crossbario/autobahn-python/autobahn/xbr/__init__.py", line 56, in <module>
    from autobahn.xbr._config import load_or_create_profile, UserConfig, Profile  # noqa
  File "/home/om26er/scm/crossbario/autobahn-python/autobahn/xbr/_config.py", line 60, in <module>
    class Profile(object):
  File "/home/om26er/scm/crossbario/autobahn-python/autobahn/xbr/_config.py", line 62, in Profile
    log = make_logger()
  File "/home/om26er/scm/crossbario/xbr-www/venv/lib/python3.8/site-packages/txaio/_unframework.py", line 41, in _throw_usage_error
    raise RuntimeError(
RuntimeError: To use txaio, you must first select a framework with .use_twisted() or .use_asyncio()
```
That kind of break tests at many places since the imports previously did not select a txaio framework.

**Comment by oberstet** [comment]
yes, you need to select the networking framework

**Comment by meejah** [comment]
I think what's going on is that "usually" you were able to select it by importing from `autobahn.twisted.*` or from `autobahn.asyncio.*` ... is `self.log` even used here?
