### ISSUE TITLE
xbr:jinja2 missing dependency

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-python#1447]
missing dependency for `xbr` dist flavor:

```
(cpy390_5) oberstet@intel-nuci7:~$ xbrnetwork version
Traceback (most recent call last):
  File "/home/oberstet/cpy390_5/bin/xbrnetwork", line 5, in <module>
    from autobahn.xbr._cli import _main
  File "/home/oberstet/cpy390_5/lib/python3.9/site-packages/autobahn/xbr/_cli.py", line 33, in <module>
    from jinja2 import Environment, FileSystemLoader
ModuleNotFoundError: No module named 'jinja2'
```

**Comment by oberstet** [comment]
fixed via https://github.com/crossbario/autobahn-python/pull/1448
