### ISSUE TITLE
websocket compression regression: TB from "Invalid initialization option"

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-python#1477]
```
2021-03-16T18:04:47+0100 Unhandled Error
Traceback (most recent call last):
  File "/home/oberstet/scm/crossbario/autobahn-python/wstest/venv_cpy3_tx/lib/python3.9/site-packages/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/oberstet/scm/crossbario/autobahn-python/wstest/venv_cpy3_tx/lib/python3.9/site-packages/twisted/python/log.py", line 85, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/oberstet/scm/crossbario/autobahn-python/wstest/venv_cpy3_tx/lib/python3.9/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/oberstet/scm/crossbario/autobahn-python/wstest/venv_cpy3_tx/lib/python3.9/site-packages/twisted/python/context.py", line 83, in callWithContext
    return func(*args, **kw)
--- <exception caught here> ---
  File "/home/oberstet/scm/crossbario/autobahn-python/wstest/venv_cpy3_tx/lib/python3.9/site-packages/twisted/internet/posixbase.py", line 687, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/oberstet/scm/crossbario/autobahn-python/wstest/venv_cpy3_tx/lib/python3.9/site-packages/twisted/internet/tcp.py", line 246, in doRead
    return self._dataReceived(data)
  File "/home/oberstet/scm/crossbario/autobahn-python/wstest/venv_cpy3_tx/lib/python3.9/site-packages/twisted/internet/tcp.py", line 251, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/oberstet/scm/crossbario/autobahn-python/wstest/venv_cpy3_tx/lib/python3.9/site-packages/autobahn/twisted/websocket.py", line 290, in dataReceived
    self._dataReceived(data)
  File "/home/oberstet/scm/crossbario/autobahn-python/wstest/venv_cpy3_tx/lib/python3.9/site-packages/autobahn/websocket/protocol.py", line 1207, in _dataReceived
    self.consumeData()
  File "/home/oberstet/scm/crossbario/autobahn-python/wstest/venv_cpy3_tx/lib/python3.9/site-packages/autobahn/websocket/protocol.py", line 1236, in consumeData
    self.processHandshake()
  File "/home/oberstet/scm/crossbario/autobahn-python/wstest/venv_cpy3_tx/lib/python3.9/site-packages/autobahn/websocket/protocol.py", line 3854, in processHandshake
    self.consumeData()
  File "/home/oberstet/scm/crossbario/autobahn-python/wstest/venv_cpy3_tx/lib/python3.9/site-packages/autobahn/websocket/protocol.py", line 1219, in consumeData
    while self.processData() and self.state != WebSocketProtocol.STATE_CLOSED:
  File "/home/oberstet/scm/crossbario/autobahn-python/wstest/venv_cpy3_tx/lib/python3.9/site-packages/autobahn/websocket/protocol.py", line 1579, in processData
    fr = self.onFrameEnd()
  File "/home/oberstet/scm/crossbario/autobahn-python/wstest/venv_cpy3_tx/lib/python3.9/site-packages/autobahn/websocket/protocol.py", line 1704, in onFrameEnd
    self._onMessageEnd()
  File "/home/oberstet/scm/crossbario/autobahn-python/wstest/venv_cpy3_tx/lib/python3.9/site-packages/autobahn/twisted/websocket.py", line 318, in _onMessageEnd
    self.onMessageEnd()
  File "/home/oberstet/scm/crossbario/autobahn-python/wstest/venv_cpy3_tx/lib/python3.9/site-packages/autobahn/websocket/protocol.py", line 628, in onMessageEnd
    self._onMessage(payload, self.message_is_binary)
  File "/home/oberstet/scm/crossbario/autobahn-python/wstest/venv_cpy3_tx/lib/python3.9/site-packages/autobahn/twisted/websocket.py", line 321, in _onMessage
    self.onMessage(payload, isBinary)
  File "/home/oberstet/scm/crossbario/autobahn-python/wstest/testee_client_tx.py", line 60, in onMessage
    self.sendMessage(msg, binary)
  File "/home/oberstet/scm/crossbario/autobahn-python/wstest/venv_cpy3_tx/lib/python3.9/site-packages/autobahn/websocket/protocol.py", line 2236, in sendMessage
    self._perMessageCompress.start_compress_message()
  File "/home/oberstet/scm/crossbario/autobahn-python/wstest/venv_cpy3_tx/lib/python3.9/site-packages/autobahn/websocket/compress_deflate.py", line 636, in start_compress_message
    self._compressor = zlib.compressobj(zlib.Z_DEFAULT_COMPRESSION, zlib.DEFLATED, -self.client_max_window_bits, self.mem_level)
builtins.ValueError: Invalid initialization option
```

**Comment by oberstet** [comment]
ok, awesome: seems like zlib did allow wbits==8 historically, but it doesn't allow any longer. the permissible values are +9 to +15: The base-two logarithm of the window size.

* https://docs.python.org/3/library/zlib.html#zlib.compressobj
* https://www.zlib.net/manual.html
* https://stackoverflow.com/questions/55524471/re-compress-a-decompressed-string-with-zlib


>  The windowBits parameter is the base two logarithm of the window size (the size of the history buffer). It should be in the range 8..15 for this version of the library. Larger values of this parameter result in better compression at the expense of memory usage. The default value is 15 if deflateInit is used instead.
> For the current implementation of deflate(), a windowBits value of 8 (a window size of 256 bytes) is not supported. As a result, a request for 8 will result in 9 (a 512-byte window). In that case, providing 8 to inflateInit2() will result in an error when the zlib header with 9 is checked against the initialization of inflate(). The remedy is to not use 8 with deflateInit2() with this initialization, or at least in that case use 9 with inflateInit2(). 

```
>>> import zlib
>>> zlib.compressobj(zlib.Z_DEFAULT_COMPRESSION, zlib.DEFLATED, -9)
<zlib.Compress object at 0x7f2873a7bf50>
>>> zlib.compressobj(zlib.Z_DEFAULT_COMPRESSION, zlib.DEFLATED, -10)
<zlib.Compress object at 0x7f2873a7bea0>
>>> zlib.compressobj(zlib.Z_DEFAULT_COMPRESSION, zlib.DEFLATED, -11)
<zlib.Compress object at 0x7f2873a7bf50>
>>> zlib.compressobj(zlib.Z_DEFAULT_COMPRESSION, zlib.DEFLATED, -12)
<zlib.Compress object at 0x7f2873a7bea0>
>>> zlib.compressobj(zlib.Z_DEFAULT_COMPRESSION, zlib.DEFLATED, -13)
<zlib.Compress object at 0x7f2873a7bf50>
>>> zlib.compressobj(zlib.Z_DEFAULT_COMPRESSION, zlib.DEFLATED, -14)
<zlib.Compress object at 0x7f2873a7bea0>
>>> zlib.compressobj(zlib.Z_DEFAULT_COMPRESSION, zlib.DEFLATED, -15)
<zlib.Compress object at 0x7f2873a7bf50>
>>> zlib.compressobj(zlib.Z_DEFAULT_COMPRESSION, zlib.DEFLATED, -8)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Invalid initialization option
>>> 
```

**Comment by oberstet** [comment]
alright, testsuite is fixed via https://github.com/crossbario/autobahn-testsuite/commit/3d390350ade4aee4b48f0b84e57f59e116ec0df8
