### ISSUE TITLE
Django 3.2 Intergate with AutoBahn Twisest on Production - Secure Server 

### ISSUE THREAD

**Issue by lukenuyen02** [crossbario/autobahn-python#1507]
Django 3.2 is using a new way for secure data using web socket,[ for writing asynchronous (“async”) views, along with an entirely async-enabled request stack if you are running under ASGI.
](https://docs.djangoproject.com/en/3.2/topics/async/#asgiref.sync.sync_to_async)

I have 2 Django server and I am trying to use Auto Bathn Twisted - WebSocketClientFactory to connect with the other Django app. I followed the example for [reconnecting/client.py](https://github.com/crossbario/autobahn-python/blob/master/examples/twisted/websocket/reconnecting/client.py). As for Django 2, both connection end point were able to run vert smooth and stable, until we upgrade both of our Django to 3.2 then the Clients that have the Auto Bathn Twisted - WebSocketClientFactory is failed to send Message to the other App even though the  Web Socket is connected. 

With Django 3.2  upgrade as long as I put the ORM funciong call in the  database_sync_to_async  or sync_to_async wrapper it will send the message/ data through websocket. But Auto Bathn Twisted is using a different function to send message to the other server that cant be integrated.

For example:
if leave everything as normal, using the exactly code  following the example: 

```
class SmartiaClientProtocol(WebSocketClientProtocol):
.
.

def onOpen(self):
                logger_websocket.info("WebSocket connection open.")
                # Inintiate the function
                # self.sendHello()

                self.camera_sync()
`
`
            def camera_sync(self):
                global message

                if self.is_open:
                    message = SyncAllCamera()

                    try:
                        self.sendMessage(message)
                    except Exception as e:
                        logger_websocket.error(
                            "Fail to send message. Reason: {}".format(
                                e
                            )
                        )
                # if the ws connection is open, else then call it again later
                reactor.callLater(900, self.camera_sync)

```
```
# @sync_to_async(thread_sensitive=True)
def SyncAllCamera():
    # Sync the camera from the LPR to Proptia
    camera_obj = LPRCamera.objects.all().values(
        "alpr_camera_id",
        "lpr_computer__access_token_code",
        "lpr_computer_folder_path",
        "lpr_camera_name",
        "lpr_camera_location",
        "lpr_camera_position",
        "lpr_camera_manufacturer",
        "lpr_camera_model",
        # "wan_ip_address",
        # "wan_rtsp_port",
        "lan_ip_address",
        "lan_rtsp_port",
        "lan_webadmin_port",
        # "wan_webadmin_port",
        "mac_address",
        "serial_number",
        "web_admin_username",
        "web_admin_password",
        "lpr_camera_description",
        "is_visitor",
        "lane_type",
        "camera_status",
    )
    message = json.dumps({
        "message": "CameraSync",
        "camera": json.dumps(list(camera_obj),
                             cls=DjangoJSONEncoder)
    })
    logger_websocket.info(
        "Sync Cameras: {0}".format(camera_obj.count())
    )

    return message.encode('utf8')
```

**Here is the Error:**

```
2021-12-13 20:28:47+0000 [-] Log opened.
2021-12-13 20:28:47+0000 [-] Starting factory <smartia.management.commands.smartia_websockets.Command.handle.<locals>.SmartiaWebSocketClientFactory object at 0x7f6709d1ecd0>
[2021-12-13 20:28:47] INFO [websocket.onConnecting:583] Connecting to: <class 'datetime.datetime'> on ws://127.0.0.1:8000/ws/smartia/
[2021-12-13 20:28:47] INFO [websocket.onConnect:588] Smart.IA WebSocket connection established: <class 'datetime.datetime'>
[2021-12-13 20:28:47] INFO [websocket.onOpen:355] WebSocket connection open.
2021-12-13 20:28:47+0000 [-] Unhandled Error
        Traceback (most recent call last):
          File "/home/lnguyen/.local/share/virtualenvs/smartia-web-app-LcKlVzIz/lib/python3.9/site-packages/twisted/python/log.py", line 101, in callWithLogger
            return callWithContext({"system": lp}, func, *args, **kw)
          File "/home/lnguyen/.local/share/virtualenvs/smartia-web-app-LcKlVzIz/lib/python3.9/site-packages/twisted/python/log.py", line 85, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/home/lnguyen/.local/share/virtualenvs/smartia-web-app-LcKlVzIz/lib/python3.9/site-packages/twisted/python/context.py", line 118, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/home/lnguyen/.local/share/virtualenvs/smartia-web-app-LcKlVzIz/lib/python3.9/site-packages/twisted/python/context.py", line 83, in callWithContext
            return func(*args, **kw)
        --- <exception caught here> ---
          File "/home/lnguyen/.local/share/virtualenvs/smartia-web-app-LcKlVzIz/lib/python3.9/site-packages/twisted/internet/asyncioreactor.py", line 140, in _readOrWrite
            why = method()
          File "/home/lnguyen/.local/share/virtualenvs/smartia-web-app-LcKlVzIz/lib/python3.9/site-packages/twisted/internet/tcp.py", line 247, in doRead
            return self._dataReceived(data)
          File "/home/lnguyen/.local/share/virtualenvs/smartia-web-app-LcKlVzIz/lib/python3.9/site-packages/twisted/internet/tcp.py", line 252, in _dataReceived
            rval = self.protocol.dataReceived(data)
          File "/home/lnguyen/.local/share/virtualenvs/smartia-web-app-LcKlVzIz/lib/python3.9/site-packages/autobahn/twisted/websocket.py", line 290, in dataReceived
            self._dataReceived(data)
          File "/home/lnguyen/.local/share/virtualenvs/smartia-web-app-LcKlVzIz/lib/python3.9/site-packages/autobahn/websocket/protocol.py", line 1207, in _dataReceived
            self.consumeData()
          File "/home/lnguyen/.local/share/virtualenvs/smartia-web-app-LcKlVzIz/lib/python3.9/site-packages/autobahn/websocket/protocol.py", line 1236, in consumeData
            self.processHandshake()
          File "/home/lnguyen/.local/share/virtualenvs/smartia-web-app-LcKlVzIz/lib/python3.9/site-packages/autobahn/websocket/protocol.py", line 3847, in processHandshake
            self._onOpen()
          File "/home/lnguyen/.local/share/virtualenvs/smartia-web-app-LcKlVzIz/lib/python3.9/site-packages/autobahn/twisted/websocket.py", line 300, in _onOpen
            self.onOpen()
          File "/home/lnguyen/PycharmProjects/smartia-web-app/smartia/management/commands/smartia_websockets.py", line 359, in onOpen
            self.camera_sync()
          File "/home/lnguyen/PycharmProjects/smartia-web-app/smartia/management/commands/smartia_websockets.py", line 756, in camera_sync
            message = SyncAllCamera()
          File "/home/lnguyen/PycharmProjects/smartia-web-app/smartia/management/commands/smartia_websockets.py", line 144, in SyncAllCamera
            "camera": json.dumps(list(camera_obj),
          File "/home/lnguyen/.local/share/virtualenvs/smartia-web-app-LcKlVzIz/lib/python3.9/site-packages/django/db/models/query.py", line 262, in __len__
            self._fetch_all()
          File "/home/lnguyen/.local/share/virtualenvs/smartia-web-app-LcKlVzIz/lib/python3.9/site-packages/django/db/models/query.py", line 1324, in _fetch_all
            self._result_cache = list(self._iterable_class(self))
          File "/home/lnguyen/.local/share/virtualenvs/smartia-web-app-LcKlVzIz/lib/python3.9/site-packages/django/db/models/query.py", line 109, in __iter__
            for row in compiler.results_iter(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size):
          File "/home/lnguyen/.local/share/virtualenvs/smartia-web-app-LcKlVzIz/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1130, in results_iter
            results = self.execute_sql(MULTI, chunked_fetch=chunked_fetch, chunk_size=chunk_size)
          File "/home/lnguyen/.local/share/virtualenvs/smartia-web-app-LcKlVzIz/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1173, in execute_sql
            cursor = self.connection.cursor()
          File "/home/lnguyen/.local/share/virtualenvs/smartia-web-app-LcKlVzIz/lib/python3.9/site-packages/django/utils/asyncio.py", line 31, in inner
            raise SynchronousOnlyOperation(message)
        django.core.exceptions.SynchronousOnlyOperation: You cannot call this from an async context - use a thread or sync_to_async.


```

Base on the Django doc, I put the function that contain the ORM call in the  database_sync_to_async  or sync_to_async wrapper
I got this error:
`
[2021-12-13 21:00:51] ERROR [websocket.camera_sync:761] Fail to send message. Reason: "payload" must have type bytes, but was "<class 'coroutine'>"
`

Please guide me a way to work this out

**Comment by oberstet** [comment]
> Fail to send message. Reason: "payload" must have type bytes, but was "<class 'coroutine'>"

this usually means, you are missing an `await` ..

**Comment by lukenuyen02** [comment]
@oberstet 

i cant use await, because await has to be under async and I cant use async for autobath

**Comment by lukenuyen02** [comment]
@oberstet 

So I put it in the await and change the function to async 
```

            async def camera_sync(self):
                global message
                from smartia.models import LPRCamera

                if self.is_open:
                    message = await database_sync_to_async(SyncAllCamera)
                    try:
                        self.sendMessage(message)
                    except Exception as e:
                        logger_websocket.error(
                            "Fail to send message. Reason: {}".format(
                                e
                            )
                        )
                # if the ws connection is open, else then call it again later
                reactor.callLater(900, self.camera_sync)
```

the message has not been send and I got a message :

2021-12-14 20:32:45+0000 [-] /home/lnguyen/PycharmProjects/smartia-web-app/smartia/management/commands/smartia_websockets.py:359: builtins.RuntimeWarning: coroutine 'Command.handle.<locals>.SmartiaClientProtocol.camera_sync' was never awaited

**Comment by oberstet** [comment]
> packages/autobahn/twisted/websocket.py

it seems you are using Twisted, not asyncio. In that case, you need `yield` and `inlineCallbacks` rather than `await` and `async`, to handle co-routines. 

> Auto Bathn Twisted - WebSocketClientFactory 

missed that, but if you want to connect to a websocket server using autobahn client, you have to choose the right autobahn client classes depending on the context you run in.

I have little clue about django, but that is the context you run within .. if it is asyncio, then you need the asyncio classes from autobahn ..

**Comment by lukenuyen02** [comment]
Could you please give me a link for the example on using yield and inlineCallbacks ? I was looking through most of the example, and I could not find any. it would be great if you can have a guide for implementing it.

**Comment by lukenuyen02** [comment]
@oberstet 

For my experience with **asyncio**, at the beginning I used it for the web-sockets connection when we are still in Django 2. I followed the example [client_coroutines.py](https://github.com/crossbario/autobahn-python/blob/master/examples/asyncio/websocket/echo/client_coroutines.py). I didnt modified any from the example yet, and I keep the connection at local for testing. then I got the error `RuntimeError: Explicitly using 'twisted' already` 

that is when I moved on and used Twisted which **was working with Django 2** 

now I just re-write the code to use asyncio again, then the same error pop up: 

```
[2021-12-15 17:05:37] DEBUG [asyncio.__init__:59] Using selector: EpollSelector
Traceback (most recent call last):
  File "/home/lnguyen/PycharmProjects/smartia-web-app/manage.py", line 22, in <module>
    main()
  File "/home/lnguyen/PycharmProjects/smartia-web-app/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/lnguyen/.local/share/virtualenvs/smartia-web-app-LcKlVzIz/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/lnguyen/.local/share/virtualenvs/smartia-web-app-LcKlVzIz/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/lnguyen/.local/share/virtualenvs/smartia-web-app-LcKlVzIz/lib/python3.9/site-packages/django/core/management/__init__.py", line 257, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/lnguyen/.local/share/virtualenvs/smartia-web-app-LcKlVzIz/lib/python3.9/site-packages/django/core/management/__init__.py", line 39, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/lnguyen/PycharmProjects/smartia-web-app/smartia/management/commands/asyncio_websockets.py", line 13, in <module>
    from autobahn.asyncio.websocket import WebSocketClientProtocol, \
  File "/home/lnguyen/.local/share/virtualenvs/smartia-web-app-LcKlVzIz/lib/python3.9/site-packages/autobahn/asyncio/__init__.py", line 32, in <module>
    from autobahn.asyncio.websocket import \
  File "/home/lnguyen/.local/share/virtualenvs/smartia-web-app-LcKlVzIz/lib/python3.9/site-packages/autobahn/asyncio/websocket.py", line 33, in <module>
    txaio.use_asyncio()
  File "/home/lnguyen/.local/share/virtualenvs/smartia-web-app-LcKlVzIz/lib/python3.9/site-packages/txaio/__init__.py", line 122, in use_asyncio
    raise RuntimeError("Explicitly using '{}' already".format(_explicit_framework))
RuntimeError: Explicitly using 'twisted' already
```

I feel like Auto Bathn Twisted - WebSocketClientFactory will be a better way to go cause it was working before.

**Comment by meejah** [comment]
To clarify: you _can_ use `async def` and `await` with Twisted, so long as somewhere above you (typically at the top level) `ensureDeferred()` is called.

The latest error is most likely because you've still got an `import` line with `autobahn.twisted.*` in it somewhere in your code.

**Comment by lukenuyen02** [comment]
@meejah 
could you please explain to me more when you said "ensureDeferred() is called." this is my first time see that function.... 
I think if I can use async def and await with Twisted, it may be all I need for the project...

I will look for  `import line with autobahn.twisted.` and it may take time

**Comment by lukenuyen02** [comment]
@meejah 

I have came up with a little assumption that Django is using  twisted  within the its framework. I just did a small test by creating 2 terminal shells one from the Django root of the project, and one from Python 3 alone.

Python shell does not give me any error, but the one for Django gives me that error as soon as I do import.

**Comment by meejah** [comment]
@lukenuyen02 this is a little old but should give the general idea https://meejah.ca/blog/python3-twisted-and-asyncio

**Comment by lukenuyen02** [comment]
@meejah 

I have followed your example for the [client agent ](https://github.com/crossbario/autobahn-python/blob/fd5530cecff0be210b148bddf1e984ed31d2863c/examples/twisted/websocket/agent/client.py)

here is the code: 
```
        async def main(reactor):
            """
            Using the 'agent' interface to talk to the echo server (run
            ../echo/server.py for the server, for example)
            """
            agent = create_client_agent(reactor)
            options = {
                "headers": {
                    "x-foo": "bar",
                }
            }
            from smartia.models import AuthenticationInfoStore
            # from the Authentication model pull out the Data
            # to create the ws connection
            org_uuid = AuthenticationInfoStore.objects.first()
            uri = "?username=" + str(org_uuid.username) + "&password=" + str(
                org_uuid.password) + "&organization=" + str(
                org_uuid.last_sync_record_uuid)

            proto = await agent.open(PROPTIA_WEBSOCKET_URL + uri, options)

            def got_message(*args, **kw):
                print("on_message: args={} kwargs={}".format(args, kw))

            proto.on('message', got_message)

            await proto.is_open

            proto.sendMessage(b"i am a message\n")
            proto.sendMessage(await database_sync_to_async(SyncAllCamera)())
            await task.deferLater(reactor, 0, lambda: None)

            proto.sendClose(code=1000, reason="byebye")

            await proto.is_closed

        from twisted.internet.defer import ensureDeferred
        task.react(lambda r: ensureDeferred(main(r)))

```

i am a message got send to the server from the ws, but not the            ` proto.sendMessage(await database_sync_to_async(SyncAllCamera)())


I got the error 

`builtins.RuntimeError: await wasn't used with future
`
`


Is there any example to use ensureDeferred for the WebSocketClientProtocol ? cause it seems like this is not working out neither ....

**Comment by meejah** [comment]
if `database_sync_to_async` is not async-def (as I suspect) then you probably want `deferToThread` around it.

Otherwise, your use of `ensureDeferred` looks fine: you can then just `await` and `Deferred`s or other `async-def` functions in your code (and not call it anywhere else).

**Comment by lukenuyen02** [comment]
@meejah 

I think I might got a little bit more of understanding about what you are suggesting. Could you please give me more explaination on how to use `await` any `Deferred` like base on the code which one is  `Deferred`. how can I use  `Deferred`.

I can put `ensureDeferred` on the upper level of the code... but im not sure what is the parameter for it. base from your example I see that 
``
from twisted.internet.defer import ensureDeferred
        task.react(lambda r: ensureDeferred(main(r)))
```

`main` is the async function what is `r` ?


i have these in my code:
```
factory = SmartiaWebSocketClientFactory(PROPTIA_WEBSOCKET_URL + uri)
        factory.protocol = SmartiaClientProtocol

        # SSL client context: default
        ##
        if factory.isSecure:
            contextFactory = ssl.ClientContextFactory()
        else:
            contextFactory = None

        connectWS(factory, contextFactory)

        reactor.run()
```

how can i wrap this up with the  `ensureDeferred` ?

**Comment by lukenuyen02** [comment]
@meejah 

Not sure if that can be possible the  `ensureDeferred` only take the parameter of a function, but here i have a whole class of `SmartiaWebSocketClientFactory` with multiple function like onOpen, onMessage, onClose, .... etc.

under those function, its where I need to use the `await database_sync_to_async(SyncAllCamera)()` 
so that is why I need to wrap the whole up with  `ensureDeferred`, not sure if that this possible

**Comment by lukenuyen02** [comment]
@meejah 

for this example that I have found for using `ensureDeferred`

```
class Component(ApplicationSession):
    def onJoin(self, details):
        return ensureDeferred(self._on_join(details))

    async def _on_join(self, details):
        print("joined {}".format(details))
        await self._other_async()
```

Is there anyway that I can use ensureDeferred

**Comment by lukenuyen02** [comment]
@meejah  @oberstet 

I have comedown to this:
```

            def camera_sync(self):
                global message
                from smartia.models import LPRCamera

                if self.is_open:

                    message = yield deferToThread(sync_to_async(SyncAllCamera))

                    try:
                        yield self.sendMessage(message)
                    except Exception as e:
                        logger_websocket.error(
                            "Fail to send message. Reason: {}".format(
                                e
                            )
                        )
                # if the ws connection is open, else then call it again later
                reactor.callLater(900, self.camera_sync)
```


which there is no error and the WS connection is still open between server and client which is a good thing. 

but at the line`  message = yield deferToThread(sync_to_async(SyncAllCamera))` the message wasnt able to be sent. 

and I really dont know I suppose to use yield at that line but If I took it out I got the error: 
```
[2022-01-06 18:36:16] ERROR [websocket.camera_sync:773] Fail to send message. Reason: "payload" must have type bytes, but was "<class 'twisted.internet.defer.Deferred'>"
```
