### ISSUE TITLE
Breaking change: previous autoPingSize

### ISSUE THREAD

**Issue by klinquist** [crossbario/autobahn-python#1527]
Our microservices were connecting with option `{autoPingSize:4}`.  I believe this was the default.

All of our microservices broke with the latest autobahn.

```
Connection failed: AssertionError:
```

Changing our options to the new default of `12` fixed it, but it took us awhile to track this down.

**Comment by om26er** [comment]
attaching the traceback
```
(venv) om26er@RemotePC:~/Documents$ python3 main.py 
2022-02-25T03:10:25 Using selector: EpollSelector
2022-02-25T03:10:25 Entering re-connect loop
2022-02-25T03:10:25 trying transport 0 using connect delay 0
2022-02-25T03:10:25 connecting once using transport type "websocket" over endpoint "tcp"
2022-02-25T03:10:25 component failed: AssertionError: 
2022-02-25T03:10:25 Traceback (most recent call last):
  File "/home/om26er/Documents/venv/lib/pypy3.8/site-packages/txaio/aio.py", line 487, in done
    res = f.result()
  File "/home/om26er/Downloads/pypy3.8-v7.3.7-linux64/lib/pypy3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/home/om26er/Documents/venv/lib/pypy3.8/site-packages/txaio/aio.py", line 487, in done
    res = f.result()
  File "/home/om26er/Downloads/pypy3.8-v7.3.7-linux64/lib/pypy3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/home/om26er/Documents/venv/lib/pypy3.8/site-packages/txaio/aio.py", line 487, in done
    res = f.result()
  File "/home/om26er/Downloads/pypy3.8-v7.3.7-linux64/lib/pypy3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/home/om26er/Documents/venv/lib/pypy3.8/site-packages/txaio/aio.py", line 396, in as_future
    res = fun(*args, **kwargs)
  File "/home/om26er/Documents/venv/lib/pypy3.8/site-packages/autobahn/asyncio/component.py", line 146, in _connect_transport
    factory = _create_transport_factory(loop, transport, session_factory)
  File "/home/om26er/Documents/venv/lib/pypy3.8/site-packages/autobahn/asyncio/component.py", line 84, in _create_transport_factory
    factory.setProtocolOptions(**{k: v})
  File "/home/om26er/Documents/venv/lib/pypy3.8/site-packages/autobahn/websocket/protocol.py", line 4113, in setProtocolOptions
    assert(12 <= autoPingSize <= 125)
AssertionError

2022-02-25T03:10:25 Connection failed: AssertionError: 
2022-02-25T03:10:25 Entering re-connect loop
2022-02-25T03:10:25 trying transport 0 using connect delay 27.643005120931374
```

@oberstet I didn't find in the websocket protocol for the minimal ping payload size, there is max 125 though

**Comment by om26er** [comment]
attaching the traceback
```
(venv) om26er@RemotePC:~/Documents$ python3 main.py 
2022-02-25T03:10:25 Using selector: EpollSelector
2022-02-25T03:10:25 Entering re-connect loop
2022-02-25T03:10:25 trying transport 0 using connect delay 0
2022-02-25T03:10:25 connecting once using transport type "websocket" over endpoint "tcp"
2022-02-25T03:10:25 component failed: AssertionError: 
2022-02-25T03:10:25 Traceback (most recent call last):
  File "/home/om26er/Documents/venv/lib/pypy3.8/site-packages/txaio/aio.py", line 487, in done
    res = f.result()
  File "/home/om26er/Downloads/pypy3.8-v7.3.7-linux64/lib/pypy3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/home/om26er/Documents/venv/lib/pypy3.8/site-packages/txaio/aio.py", line 487, in done
    res = f.result()
  File "/home/om26er/Downloads/pypy3.8-v7.3.7-linux64/lib/pypy3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/home/om26er/Documents/venv/lib/pypy3.8/site-packages/txaio/aio.py", line 487, in done
    res = f.result()
  File "/home/om26er/Downloads/pypy3.8-v7.3.7-linux64/lib/pypy3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/home/om26er/Documents/venv/lib/pypy3.8/site-packages/txaio/aio.py", line 396, in as_future
    res = fun(*args, **kwargs)
  File "/home/om26er/Documents/venv/lib/pypy3.8/site-packages/autobahn/asyncio/component.py", line 146, in _connect_transport
    factory = _create_transport_factory(loop, transport, session_factory)
  File "/home/om26er/Documents/venv/lib/pypy3.8/site-packages/autobahn/asyncio/component.py", line 84, in _create_transport_factory
    factory.setProtocolOptions(**{k: v})
  File "/home/om26er/Documents/venv/lib/pypy3.8/site-packages/autobahn/websocket/protocol.py", line 4113, in setProtocolOptions
    assert(12 <= autoPingSize <= 125)
AssertionError

2022-02-25T03:10:25 Connection failed: AssertionError: 
2022-02-25T03:10:25 Entering re-connect loop
2022-02-25T03:10:25 trying transport 0 using connect delay 27.643005120931374
```

@oberstet I didn't find in the websocket protocol for the minimal ping payload size, there is max 125 though

**Comment by oberstet** [comment]
> I didn't find in the websocket protocol for the minimal ping payload size, there is max 125 though

so RFC6455 allows max 125, but minimum 0. this is also what autobahn implements at the generic websocket control frame API https://github.com/crossbario/autobahn-python/blob/4b6d825bb308d695f440be6ebe5e713af85bf143/autobahn/websocket/protocol.py#L1907

what the mentioned code refers to is the **autoPingSize** - this is a built-in specific use of websocket control frames (pings and pongs) for heatbeating a websocket connection. the behavior is autobahn specific .. however ..

> with option {autoPingSize:4}. I believe this was the default.

is true, and I actually changed the default to 12 in the last version so that it can carry both send time and send sequence

https://github.com/crossbario/autobahn-python/blob/4b6d825bb308d695f440be6ebe5e713af85bf143/autobahn/websocket/protocol.py#L1923

and this is to enable the

```
def onAutoPong(self, ping_sent, ping_seq, pong_received, pong_rtt, payload):
```

allowing to track the measured latency on websocket connections. well. useful, but apparently broke user code, so @klinquist sorry, I'm at fault:(

**Comment by oberstet** [comment]
however, let me not only apologize, but also promote this feature ... not only can you keep a websocket connection nicely connected with low latency and detect connection losses quickly, but when using WAMP, you can use the new `transaction_hash` in Calls and Publishes, and call/publish to the _same_ URI from _different_ Callers/Publishers, and then use (and track) the Calls/Events from the quickest source (and deduplicate using `transaction_hash` - or let Crossbar.io do that .. once I have added it;)

**Comment by klinquist** [comment]
That's great.. but backwards compatibility would have been great too :).   (If autoPingSize <12, log a message w/ a github issue URL describing why you should update it to get the new feature!)

**Comment by oberstet** [comment]
yes, true. and would have been easy to do as you describe. so yes, will take more care next time
