### ISSUE TITLE
CI: pyinstaller problem

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-python#1529]
```
  buildexe run-test: commands[17] | file /home/cbbuilder/xbrnetwork
  /home/cbbuilder/xbrnetwork: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=ac40f3d3f795f9ee657f59a09fbedea23c4d7e25, for GNU/Linux 2.6.32, stripped
  buildexe run-test: commands[18] | ldd /home/cbbuilder/xbrnetwork
  	linux-vdso.so.1 (0x00007ffd7f9ed000)
  	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f8acb9bc000)
  	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f8acb9a0000)
  	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f8acb97d000)
  	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8acb78b000)
  	/lib64/ld-linux-x86-64.so.2 (0x00007f8acb9db000)
  buildexe run-test: commands[19] | du -h /home/cbbuilder/xbrnetwork
  49M	/home/cbbuilder/xbrnetwork
  buildexe run-test: commands[20] | /home/cbbuilder/xbrnetwork version
  Traceback (most recent call last):
    File "PyInstaller/hooks/rthooks/pyi_rth_pkgres.py", line 16, in <module>
    File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
    File "pkg_resources/__init__.py", line 74, in <module>
    File "pkg_resources/extern/__init__.py", line 52, in create_module
    File "pkg_resources/extern/__init__.py", line 44, in load_module
  ImportError: The 'jaraco' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.
  [391934] Failed to execute script 'pyi_rth_pkgres' due to unhandled exception!
  ERROR: InvocationError for command /home/cbbuilder/xbrnetwork version (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   buildexe: commands failed
make: *** [Makefile:115: build_exe] Fehler 1
Error: Process completed with exit code 2.
```

https://pypi.org/project/jaraco.packaging/

**Comment by oberstet** [comment]
fixed https://github.com/crossbario/autobahn-python/actions?query=workflow%3Apyinstaller
