### ISSUE TITLE
Can not import twisted.util

### ISSUE THREAD

**Issue by JakubHazik** [crossbario/autobahn-python#1559]
Can not import `import autobahn.twisted.util`

```
Traceback (most recent call last):
  File "/home/jakub/PycharmProjects/pythonProject/main.py", line 2, in <module>
    import autobahn.twisted.util
  File "/home/jakub/PycharmProjects/pythonProject/.venv/lib/python3.8/site-packages/autobahn/twisted/__init__.py", line 36, in <module>
    from autobahn.twisted.util import sleep
  File "/home/jakub/PycharmProjects/pythonProject/.venv/lib/python3.8/site-packages/autobahn/twisted/util.py", line 192, in <module>
    def extract_peer_certificate(transport: TLSMemoryBIOProtocol) -> Optional[Dict[str, Any]]:
NameError: name 'TLSMemoryBIOProtocol' is not defined
```
The issue occurred when this import failed inside try-except scope:
https://github.com/crossbario/autobahn-python/blob/308b5c74b25bb58b690182d899fc71cf86b07e46/autobahn/twisted/util.py#L120

Looks like a bad indentation for this method?
https://github.com/crossbario/autobahn-python/blob/308b5c74b25bb58b690182d899fc71cf86b07e46/autobahn/twisted/util.py#L192

**Comment by yan12125** [comment]
FWIW, I got the same issue and the error is gone after `pip install pyopenssl`
