### ISSUE TITLE
Crossbar won't start when Installed with Pip

### ISSUE THREAD

**Issue by rubyonrails3** [crossbario/autobahn-python#1629]
Hi, I was trying to run crossbar on my Macbook and after installing the crossbar, it won't starts 
and most probably this commit might be the reason https://github.com/crossbario/autobahn-python/commit/8c57aff8f0d01b64b0e3fa32ddd5780cd43dd1bd 

```
Traceback (most recent call last):
  File "/Users/ismail/work/corssbar-router-2/bin/crossbar", line 5, in <module>
    from crossbar import run
  File "/Users/ismail/work/corssbar-router-2/lib/python3.10/site-packages/crossbar/__init__.py", line 15, in <module>
    from crossbar._util import hl
  File "/Users/ismail/work/corssbar-router-2/lib/python3.10/site-packages/crossbar/_util.py", line 22, in <module>
    from crossbar.common.checkconfig import InvalidConfigException
  File "/Users/ismail/work/corssbar-router-2/lib/python3.10/site-packages/crossbar/common/checkconfig.py", line 22, in <module>
    from autobahn.wamp.message import _URI_PAT_STRICT_NON_EMPTY, _URI_PAT_STRICT_LAST_EMPTY, \
ImportError: cannot import name 'identity_realm_name_category' from 'autobahn.wamp.message'.  Did you mean: 'identify_realm_name_category'?
````

**Comment by om26er** [comment]
The issue should be created for https://github.com/crossbario/crossbar repo. In general you might want to just use the Crossbar docker container

**Comment by rubyonrails3** [comment]
> The issue should be created for https://github.com/crossbario/crossbar repo. In general you might want to just use the Crossbar docker container

Makes sense.

**Comment by oberstet** [comment]
yeah, the Docker images or Ubuntu snaps, otherwise - for developing on Crossbar.io itself only - you need to install from source.
