### ISSUE TITLE
Coherent treatment of serialization formats

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-python#461]
WAMP supports the use of different serialization formats, namely JSON and MsgPack as of today (and potentially more in the future).

More so, WAMP not only provides the use of one of multiple serialization formats in one larger system, but the transparent use of different serialization formats by different clients at the same time.

WAMP routers are assumed to be able to transparently translate the different serialization formats used by different clients.

So far so good. I think the goal is sufficiently clear and desirable.

However, there are multiple issues and corner cases we need to address. I am going to start this discussion in this repo, as we can use Python code to illustrate. However, it might very well be the case that we need to add material to the WAMP spec text as well, to clarify the corner cases.

**Comment by oberstet** [comment]
The WAMP spec [here](https://github.com/tavendo/WAMP/blob/master/spec/basic.md#messages) notes, that `param1|dict` shall denote a dictionary where the keys are (unique) strings.

In particular, the keys are not allowed to be say integers. Also note, that this notation does NOT say anything about keys of dictionaries embedded inside the value of `param1`.

That is, of the following three only the first is a valid value in the above sense

```python
>>> {u'foo': 23}
{u'foo': 23}
>>> {42: 23}
{42: 23}
>>> {'foo': 23}
{'foo': 23}
```

while the following are both valid

```python
>>> {u'foo': {u'bar': 23}}
{u'foo': {u'bar': 23}}
>>> {u'foo': {42: 23}}
{u'foo': {42: 23}}
```

The notation `param1|dict` is later used to specify application payload fields in WAMP messages and in options and details fields of WAMP messages.

Positional application payload fields are systematically denoted `args|list` while keyword-based application payload is denoted `kwargs|dict`.

The thinking behind this is: a WAMP implementation should be able to directly use the `kwargs` dictionary in calling host language procedures using the native keyword-based calling convention of the host language. If there is such. As for Python or PL/SQL for example.

**Comment by oberstet** [comment]
Here is Python 2 behavior with the builtin JSON:

```console
>>> value = {u'param1': 1, 'param2': 2, 23: 3, .3: 4, False: 5, None: 6}
>>> packed = json.dumps(value, separators=(',', ':'), ensure_ascii=False)
>>> packed
u'{"False":5,"null":6,"0.3":4,"param2":2,"param1":1,"23":3}'
>>> json.loads(packed)
{u'False': 5, u'23': 3, u'0.3': 4, u'param2': 2, u'param1': 1, u'null': 6}
>>> 
```

and here is Python 3:

```console
>>> import json
>>> value = {u'param1': 1, 'param2': 2, 23: 3, .3: 4, False: 5, None: 6}
>>> packed = json.dumps(value, separators=(',', ':'), ensure_ascii=False)
>>> packed
'{"0.3":4,"false":5,"null":6,"23":3,"param1":1,"param2":2}'
>>> json.loads(packed)
{'0.3': 4, 'param2': 2, 'false': 5, 'param1': 1, 'null': 6, '23': 3}
```

Invalid input in Python 2 is treated like this:

```console
>>> json.loads('{23: 3}')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/oberstet/python279/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/home/oberstet/python279/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/oberstet/python279/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 1 column 2 (char 1)
```

and in Python 3:

```console
>>> json.loads('{23: 3}')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/oberstet/python342/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/home/oberstet/python342/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/oberstet/python342/lib/python3.4/json/decoder.py", line 359, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
```

**Comment by oberstet** [comment]
Now, what about MsgPack?

Here is Python 2:

```console
>>> value = {u'param1': 1, 'param2': 2, 23: 3, .3: 4, False: 5, None: 6}
>>> packed = msgpack.packb(value, use_bin_type=True)
>>> packed
'\x86\xc2\x05\xc0\x06\xcb?\xd3333333\x04\xc4\x06param2\x02\xa6param1\x01\x17\x03'
>>> msgpack.unpackb(packed, encoding='utf-8')
{False: 5, None: 6, 0.3: 4, 'param2': 2, u'param1': 1, 23: 3}
```

and Python 3:

```console
>>> value = {u'param1': 1, 'param2': 2, 23: 3, .3: 4, False: 5, None: 6}
>>> packed = msgpack.packb(value, use_bin_type=True)
>>> packed
b'\x86\xcb?\xd3333333\x04\xc2\x05\xc0\x06\x17\x03\xa6param1\x01\xa6param2\x02'
>>> msgpack.unpackb(packed, encoding='utf-8')
{0.3: 4, False: 5, None: 6, 23: 3, 'param1': 1, 'param2': 2}
```

**Comment by oberstet** [comment]
we have quite exhaustive CI tests now for that https://github.com/crossbario/autobahn-python/blob/master/autobahn/wamp/test/test_serializer.py which include _cross_tripping of various values across different serializers (all supported)

this should be fine ..
