### ISSUE TITLE
ImportError: cannot import name longpoll while running crossbar python example

### ISSUE THREAD

**Issue by voidabhi** [crossbario/autobahn-python#561]
OS: `Mac OSX 10.10.2`
Python Version: `2.7.6`
Crossbar: `0.11.1`
Autobahn: `0.11.0`

```
2015-12-03T13:21:52+0530 [Controller  77106] Stale Crossbar.io PID file (pointing to non-existing process with PID 77030) /Users/voidabhi/stuff/py/hello/.crossbar/node.pid removed
2015-12-03T13:21:52+0530 [Controller  77106]      __  __  __  __  __  __      __     __
2015-12-03T13:21:52+0530 [Controller  77106]     /  `|__)/  \/__`/__`|__) /\ |__)  |/  \
2015-12-03T13:21:52+0530 [Controller  77106]     \__,|  \\__/.__/.__/|__)/~~\|  \. |\__/
2015-12-03T13:21:52+0530 [Controller  77106]                                         
2015-12-03T13:21:52+0530 [Controller  77106]     Version: 0.11.1     
2015-12-03T13:21:52+0530 [Controller  77106] 
2015-12-03T13:21:52+0530 [Controller  77106] Starting from node directory /Users/voidabhi/stuff/py/bingo-backend/cb/.crossbar
2015-12-03T13:21:53+0530 [Controller  77106] Traceback (most recent call last):
2015-12-03T13:21:53+0530 [Controller  77106]   File "/usr/local/bin/crossbar", line 9, in <module>
2015-12-03T13:21:53+0530 [Controller  77106]     load_entry_point('crossbar==0.11.1', 'console_scripts', 'crossbar')()
2015-12-03T13:21:53+0530 [Controller  77106]   File "/Library/Python/2.7/site-packages/crossbar/controller/cli.py", line 834, in run
2015-12-03T13:21:53+0530 [Controller  77106]     options.func(options, reactor=reactor)
2015-12-03T13:21:53+0530 [Controller  77106]   File "/Library/Python/2.7/site-packages/crossbar/controller/cli.py", line 523, in run_command_start
2015-12-03T13:21:53+0530 [Controller  77106]     from crossbar.controller.node import Node
2015-12-03T13:21:53+0530 [Controller  77106]   File "/Library/Python/2.7/site-packages/crossbar/controller/node.py", line 49, in <module>
2015-12-03T13:21:53+0530 [Controller  77106]     from crossbar.worker.router import RouterRealm
2015-12-03T13:21:53+0530 [Controller  77106]   File "/Library/Python/2.7/site-packages/crossbar/worker/router.py", line 50, in <module>
2015-12-03T13:21:53+0530 [Controller  77106]     from crossbar.twisted.resource import StaticResource, StaticResourceNoListing
2015-12-03T13:21:53+0530 [Controller  77106]   File "/Library/Python/2.7/site-packages/crossbar/twisted/resource.py", line 42, in <module>
2015-12-03T13:21:53+0530 [Controller  77106]     from autobahn.twisted import longpoll
2015-12-03T13:21:53+0530 [Controller  77106] ImportError: cannot import name longpoll
```

**Comment by voidabhi** [comment]
@oberstet any specific reason for closing?

**Comment by stopthatcow** [comment]
looks like this is an issue with autobahn 0.11.0. Reverting to 0.10.9 seems to solve it. Unfortunately as crossbar doesn't pin it's version this will remain broken until autobahn fixes its breaking interface or crossbar pins to 0.10.9

**Comment by meejah** [comment]
Looks like longpoll was moved to crossbar, so also upgrading crossbar to master would likely work. But yes, until there's a release of crossbar with longpoll in it, downgrading autobahn is likely the best option ...

**Comment by stopthatcow** [comment]
This is likely to break older versions of crossbar (I'm using crossbar 0.11.0) as well as it doesn't pin a version of autobahn in its dependencies. BTW, where can I find release notes so I can see what changed in 0.11.1?

**Comment by remisharrock** [comment]
I have this issue also, why closing it ?

**Comment by kuc2477** [comment]
+1

**Comment by travisn** [comment]
+1

**Comment by oberstet** [comment]
yeah, sorry. fixed in https://pypi.python.org/pypi/crossbar/0.11.2

**Comment by oberstet** [comment]
@voidabhi @remisharrock I misunderstood the issue (wasn't looking closely enough) - it's a crossbar/autobahn version incompat.

@stopthatcow we totally should have release notes;) - means: there are none. crossbar is still moving fast, and we (as a project) simply don't have the resources for everything. a lame excuse, I know. sorry.

**Comment by meejah** [comment]
@stopthatcow For a quick-and-dirty idea of what changes between tags, it's of course possible via Git: "git log --oneline v0.11.0..v0.11.2". We've also been using "milestones" on GitHub more recently, so that can give you a clue as to which issues went into which release. I know neither of those replace proper release-notes :/

...and if you have the motivation, a PR against ``docs/changelog.rst`` would be a great way to contribute to the project! :)

**Comment by stopthatcow** [comment]
Thanks @meejah looks like I will be trying out 0.11.2
