### ISSUE TITLE
Doc generation and txaio explicit framework selection issue

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-python#584]
```console
(python279_1)oberstet@thinkpad-t430s:~/scm/crossbario/autobahn-python/doc$ make publish
rm -rf _build
rm -rf _build_uploaded
rm -rf _static/img/gen
rm -rf _test
rm -rf _spelling
#scons
sphinx-build -A cstatic="//tavendo-common-static.s3-eu-west-1.amazonaws.com" -b html . _build
Running Sphinx v1.3.5
making output directory...
Initializing Spelling Checker
loading pickled environment... not yet created
loading intersphinx inventory from http://docs.python.org/2/objects.inv...
loading intersphinx inventory from http://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://pythonhosted.org/six/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 15 source files that are out of date
updating environment: 15 added, 0 changed, 0 removed
reading sources... [100%] websocket/programming                                                                                                                             
/home/oberstet/scm/crossbario/autobahn-python/doc/reference/autobahn.twisted.rst:13: WARNING: autodoc: failed to import module u'autobahn.twisted.choosereactor'; the following exception was raised:
Traceback (most recent call last):
  File "/home/oberstet/python279_1/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/oberstet/scm/crossbario/autobahn-python/autobahn/twisted/__init__.py", line 34, in <module>
    from autobahn.twisted.choosereactor import install_reactor
  File "/home/oberstet/scm/crossbario/autobahn-python/autobahn/twisted/choosereactor.py", line 32, in <module>
    txaio.use_twisted()
  File "/home/oberstet/scm/crossbario/txaio/txaio/__init__.py", line 100, in use_twisted
    raise RuntimeError("Explicitly using '{}' already".format(_explicit_framework))
RuntimeError: Explicitly using 'asyncio' already
```

**Comment by meejah** [comment]
Hmmm....I wonder if we can split the autodoc generation into two steps. Or, can we run some of our own Python code after asyncio is done and before Twisted (to, e.g., monkey-patch txaio so it no longer does the error like ``txaio._explicit_framework = None``).

**Comment by oberstet** [comment]
fixed on trunk via monkey patching https://github.com/crossbario/autobahn-python/blob/master/docs/conf.py#L37
