### ISSUE TITLE
Unicode chars break the library when WAMP Debug is used with JSON Serialization

### ISSUE THREAD

**Issue by pramukta** [crossbario/autobahn-python#599]
So I found this kindof subtle issue.  Specifically, when `self.logFrames = True`, the `logTxFrames` and `logRxFrames` methods in `autobahn/websocket/protocol.py` call `binascii.b2a_hex` on the frame payload.  This is fine when the payload is msgpack binary since that has been encoded into a byte string already.  However, when the payload is JSON it is a unicode payload which gets implicitly converted to a byte string using the ascii codec.  As a result, if there is a unicode character in there (for example `u"\u2639"`) an exception is thrown from the logger that looks like this:

```Shell
2016-02-09T12:29:21-0600 Unhandled error in Deferred:
2016-02-09T12:29:21-0600 Traceback (most recent call last):
  File "/Users/prak/anaconda/envs/bonetest/lib/python2.7/site-packages/autobahn/wamp/websocket.py", line 95, in onMessage
    self._session.onMessage(msg)
  File "/Users/prak/anaconda/envs/bonetest/lib/python2.7/site-packages/autobahn/wamp/protocol.py", line 639, in onMessage
    txaio.add_callbacks(on_reply, success, error)
  File "/Users/prak/anaconda/envs/bonetest/lib/python2.7/site-packages/txaio/tx.py", line 392, in add_callbacks
    future.addCallbacks(callback, errback)
  File "/Users/prak/anaconda/envs/bonetest/lib/python2.7/site-packages/twisted/internet/defer.py", line 306, in addCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/Users/prak/anaconda/envs/bonetest/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/Users/prak/anaconda/envs/bonetest/lib/python2.7/site-packages/autobahn/wamp/protocol.py", line 601, in success
    self._transport.send(reply)
  File "/Users/prak/anaconda/envs/bonetest/lib/python2.7/site-packages/autobahn/wamp/websocket.py", line 123, in send
    self.sendMessage(payload, isBinary)
  File "/Users/prak/anaconda/envs/bonetest/lib/python2.7/site-packages/autobahn/websocket/protocol.py", line 2211, in sendMessage
    self.sendFrame(opcode=opcode, payload=payload, sync=sync, rsv=4 if sendCompressed else 0)
  File "/Users/prak/anaconda/envs/bonetest/lib/python2.7/site-packages/autobahn/websocket/protocol.py", line 1836, in sendFrame
    self.logTxFrame(frameHeader, payload, payload_len, chopsize, sync)
  File "/Users/prak/anaconda/envs/bonetest/lib/python2.7/site-packages/autobahn/websocket/protocol.py", line 1164, in logTxFrame
    self.log.debug("TX Frame to %s : fin = %s, rsv = %s, opcode = %s, mask = %s, length = %s, repeat_length = %s, chopsize = %s, sync = %s, payload = %s" % info)
exceptions.UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 11: ordinal not in range(128)
```

I replicated this in an isolated case by modifying the `rpc/arguments` example, enabling debugging and adding in that unicode character to the payload.  I used the bonefish router to test because it was easy to disable msgpack on the command line (and I had a build handy) but this exception is post-invocation and pre-response so it would happen in any router.  Disabling debug mode makes things work again.  This is tested on autobahn v0.12.1 (the latest on pypi), Python 2.7, using Twisted, though likely applies to other cases.

Any thoughts on how to best address it?  Thanks.

**Comment by meejah** [comment]
Should be addressed by #606 -- please re-open if not.
