### ISSUE TITLE
upgrading to autobahn v0.12.1 does not install pytrie

### ISSUE THREAD

**Issue by MrYsLab** [crossbario/autobahn-python#604]
I am using autobahn[asyncio] and when I either do a new install or pip install autobahn --upgrade, pytrie is not loaded. I have to manually load it.

**Comment by oberstet** [comment]
can you post the traceback?

I can't reproduce:

```console
oberstet@corei7ub1310:~$ ./cpy351/bin/virtualenv ~/cpy351_3
Using base prefix '/home/oberstet/cpy351'
New python executable in /home/oberstet/cpy351_3/bin/python3
Also creating executable in /home/oberstet/cpy351_3/bin/python
Installing setuptools, pip, wheel...done.
oberstet@corei7ub1310:~$ source ./cpy351_3/bin/activate
(cpy351_3) oberstet@corei7ub1310:~$ ./cpy351_3/bin/pip install autobahn[asyncio]
Collecting autobahn[asyncio]
Collecting txaio>=2.2.1 (from autobahn[asyncio])
Collecting six>=1.10.0 (from autobahn[asyncio])
  Using cached six-1.10.0-py2.py3-none-any.whl
Installing collected packages: six, txaio, autobahn
Successfully installed autobahn-0.12.1 six-1.10.0 txaio-2.2.1
(cpy351_3) oberstet@corei7ub1310:~$ python
Python 3.5.1 (default, Jan 22 2016, 12:36:22) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import autobahn
>>> 
```

**Comment by MrYsLab** [comment]
At line 134 of setup.py:
```
# enforce use of bundled libsodium
os.environ['SODIUM_INSTALL'] = 'bundled'
extras_require_encryption = [
    'pynacl>=1.0',              # Apache license
    'pytrie>=0.2',              # BSD license
    'pyqrcode>=1.1'             # BSD license
]
```

When I install autobahn I do not see pytrie being pulled in:
```
sudo -H pip3 install autobahn
Collecting autobahn
  Downloading autobahn-0.12.1.tar.gz (163kB)
    100% |████████████████████████████████| 163kB 1.1MB/s 
Requirement already satisfied (use --upgrade to upgrade): six>=1.10.0 in /usr/local/lib/python3.5/dist-packages (from autobahn)
Requirement already satisfied (use --upgrade to upgrade): txaio>=2.2.1 in /usr/local/lib/python3.5/dist-packages (from autobahn)
Building wheels for collected packages: autobahn
  Running setup.py bdist_wheel for autobahn ... done
  Stored in directory: /root/.cache/pip/wheels/b6/5c/08/8d7c32109110657246429c6443e4dde3358b5d226d06f3766b
Successfully built autobahn
Installing collected packages: autobahn
Successfully installed autobahn-0.12.1
```

Now when I run my application:

```
$ ./pymata_iot.pyTraceback (most recent call last):
  File "./pymata_iot.py", line 27, in <module>
    from autobahn.asyncio.websocket import WebSocketServerProtocol, \
  File "/usr/local/lib/python3.5/dist-packages/autobahn/asyncio/__init__.py", line 38, in <module>
    from autobahn.asyncio.wamp import ApplicationSession
  File "/usr/local/lib/python3.5/dist-packages/autobahn/asyncio/wamp.py", line 32, in <module>
    from autobahn.wamp import protocol
  File "/usr/local/lib/python3.5/dist-packages/autobahn/wamp/protocol.py", line 42, in <module>
    from autobahn.wamp.keyring import EncryptedPayload
  File "/usr/local/lib/python3.5/dist-packages/autobahn/wamp/keyring.py", line 64, in <module>
    from pytrie import StringTrie
ImportError: No module named 'pytrie'
```

After do a pip install of pytrie, my application runs without any exceptions.

Please let me know if you need any additional information. 

Thanks.

**Comment by meejah** [comment]
Looks like you're importing a thing (autobahn.wamp.keyring) which needs encryption, so you should install like ``pip install autobahn[asyncio,encryption]``

**Comment by MrYsLab** [comment]
@meejah Since I have not changed anything on my end at all and my install worked without issue until this release, I believe this is a problem with changes made to the Autobahn distro. I am not using encryption and have not done anything to bring it in.

You can find my setup.py here:
https://github.com/MrYsLab/pymata-aio/blob/master/setup.py

**Comment by oberstet** [comment]
There is a small issue here, which I presume is trigger because NaCl was installed (not from Autobahn), but not pytrie. And the guard only checks for the former https://github.com/crossbario/autobahn-python/blob/master/autobahn/wamp/cryptobox.py#L40

I am going to work on WAMP-cryptobox again soonish, and fix up the import guarding ..

@MrYsLab for now, you can just do `pip install autobahn[all]` - that will install all deps.

**Comment by MrYsLab** [comment]
Thank you.

**Comment by warner** [comment]
Thanks for the excellent module!

I'm seeing something similar with autobahn-0.13.1. My setup.py has `install_requires=[.."autobahn"]`, and my code does `from autobahn.twisted import websocket`:

```
File ".../src/wormhole_server/rendezvous_websocket.py", line 4, in <module>
    from autobahn.twisted import websocket
  File ".../ve/lib/python2.7/site-packages/autobahn/twisted/__init__.py", line 58, in <module>
    from autobahn.twisted.wamp import ApplicationSession
  File ".../ve/lib/python2.7/site-packages/autobahn/twisted/wamp.py", line 35, in <module>
    from autobahn.wamp import protocol
  File ".../ve/lib/python2.7/site-packages/autobahn/wamp/protocol.py", line 43, in <module>
    from autobahn.wamp.cryptobox import EncryptedPayload
  File ".../ve/lib/python2.7/site-packages/autobahn/wamp/cryptobox.py", line 64, in <module>
    from pytrie import StringTrie
exceptions.ImportError: No module named pytrie
```
`pip install autobahn` and `pip install autobahn[twisted]` don't install the missing pytrie. `pip install autobahn[encryption]` would, but it also pulls in `pyqrcode` which I don't need.

Maybe `autobahn/twisted/__init__.py` shouldn't import `ApplicationSession` from `wamp`, and leave the importing of WAMP stuff (including `wamp/cryptobox.py`) up to applications that ask for it (with `from autobahn.twisted.wamp import ApplicationSession`)?

**Comment by oberstet** [comment]
@warner works for me:

```console
oberstet@corei7ub1310:~$ ./cpy351/bin/virtualenv ~/cpy351_6
Using base prefix '/home/oberstet/cpy351'
New python executable in /home/oberstet/cpy351_6/bin/python3
Also creating executable in /home/oberstet/cpy351_6/bin/python
Installing setuptools, pip, wheel...done.
oberstet@corei7ub1310:~$ source ~/cpy351_6/bin/activate
(cpy351_6) oberstet@corei7ub1310:~$ pip install autobahn[twisted]
Collecting autobahn[twisted]
Collecting six>=1.10.0 (from autobahn[twisted])
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting txaio>=2.3.0 (from autobahn[twisted])
  Using cached txaio-2.3.1-py2.py3-none-any.whl
Collecting zope.interface>=4.1.3 (from autobahn[twisted])
Collecting Twisted>=15.5 (from autobahn[twisted])
Requirement already satisfied (use --upgrade to upgrade): setuptools in ./cpy351_6/lib/python3.5/site-packages (from zope.interface>=4.1.3->autobahn[twisted])
Installing collected packages: six, txaio, zope.interface, Twisted, autobahn
Successfully installed Twisted-16.1.1 autobahn-0.13.1 six-1.10.0 txaio-2.3.1 zope.interface-4.1.3
You are using pip version 8.0.2, however version 8.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(cpy351_6) oberstet@corei7ub1310:~$ python
Python 3.5.1 (default, Apr 16 2016, 16:23:21) 
[GCC 4.2.1 Compatible Ubuntu Clang 3.4 (tags/RELEASE_34/final)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from autobahn.twisted import websocket
>>> 
```

**Comment by oberstet** [comment]
ahh. now. this happens when you have pynacl, but not from installing `autobahn[encryption]`, but elsewhere:

```console
(cpy351_6) oberstet@corei7ub1310:~$ pip install pynacl
Collecting pynacl
Requirement already satisfied (use --upgrade to upgrade): six in ./cpy351_6/lib/python3.5/site-packages (from pynacl)
Collecting cffi>=1.1.0 (from pynacl)
Collecting pycparser (from cffi>=1.1.0->pynacl)
Installing collected packages: pycparser, cffi, pynacl
Successfully installed cffi-1.5.2 pycparser-2.14 pynacl-1.0.1
You are using pip version 8.0.2, however version 8.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(cpy351_6) oberstet@corei7ub1310:~$ python
Python 3.5.1 (default, Apr 16 2016, 16:23:21) 
[GCC 4.2.1 Compatible Ubuntu Clang 3.4 (tags/RELEASE_34/final)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from autobahn.twisted import websocket
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/oberstet/cpy351_6/lib/python3.5/site-packages/autobahn/twisted/__init__.py", line 58, in <module>
    from autobahn.twisted.wamp import ApplicationSession
  File "/home/oberstet/cpy351_6/lib/python3.5/site-packages/autobahn/twisted/wamp.py", line 35, in <module>
    from autobahn.wamp import protocol
  File "/home/oberstet/cpy351_6/lib/python3.5/site-packages/autobahn/wamp/protocol.py", line 43, in <module>
    from autobahn.wamp.cryptobox import EncryptedPayload
  File "/home/oberstet/cpy351_6/lib/python3.5/site-packages/autobahn/wamp/cryptobox.py", line 64, in <module>
    from pytrie import StringTrie
ImportError: No module named 'pytrie'
>>> 
```

so yes, bug. the guarding in Autobahn needs to test for pytrie too ..

**Comment by warner** [comment]
Ah, I should have mentioned that I'm depending upon pynacl for other reasons. Thanks for the quick fix!
