### ISSUE TITLE
autobahn fails on Python 2.6 due to formatting errors

### ISSUE THREAD

**Issue by rutsky** [crossbario/autobahn-python#614]
Python 2.6 doesn't support `"{}".format(...)`, only `"{0}".format(...)`.
This code fails:
https://github.com/crossbario/autobahn-python/blame/master/autobahn/twisted/__init__.py#L86

```
Traceback (most recent call last):

  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/twisted/trial/runner.py", line 556, in loadPackage

    module = modinfo.load()

  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/twisted/python/modules.py", line 383, in load

    return self.pathEntry.pythonPath.moduleLoader(self.name)

  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/twisted/python/reflect.py", line 506, in namedAny

    topLevelPackage = _importAndCheckStack(trialname)

  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/twisted/python/reflect.py", line 442, in _importAndCheckStack

    return __import__(importName)

  File "/home/travis/build/buildbot/buildbot/master/buildbot/test/unit/test_www_service.py", line 25, in <module>

    from buildbot.www import service

  File "/home/travis/build/buildbot/buildbot/master/buildbot/www/service.py", line 27, in <module>

    from buildbot.www import ws

  File "/home/travis/build/buildbot/buildbot/master/buildbot/www/ws.py", line 22, in <module>

    from autobahn.twisted.resource import WebSocketResource

  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/autobahn/twisted/__init__.py", line 86, in <module>

    __ident__ = u'Autobahn/{}-Twisted/{}-{}/{}'.format(autobahn.__version__, twisted.__version__, platform.python_implementation(), '.'.join([str(x) for x in list(sys.version_info[:3])]))

exceptions.ValueError: zero length field name in format
```

**Comment by rutsky** [comment]
Looks like this issue introduced in commit https://github.com/crossbario/autobahn-python/commit/39cba40689e5147187d3dcfaa099587ee6f2b1aa in 0.13.0 release.

**Comment by oberstet** [comment]
We don't support Python 2.6 any longer

**Comment by rutsky** [comment]
Congratulations! :)
