### ISSUE TITLE
Sample code not working on pypy

### ISSUE THREAD

**Issue by ricyje** [crossbario/autobahn-python#686]
Running the following sample:

    from twisted.internet.defer import inlineCallbacks
    from autobahn.twisted.wamp import ApplicationSession, ApplicationRunner

    class MyComponent(ApplicationSession):

    @inlineCallbacks
    def onJoin(self, details):
        print("session joined")
        # can do subscribes, registers here e.g.:
        # yield self.subscribe(...)
        # yield self.register(...)

    if __name__ == '__main__':
      runner = ApplicationRunner(url=u"ws://localhost:8080/ws", realm=u"realm1")
      runner.run(MyComponent)

Gives this output with version 14.1 on PyPy 5.1.1
```
2016-05-31T13:31:20-0700 session joined
2016-05-31T13:31:20-0700 While firing onJoin: Traceback (most recent call last):
  File "/home/x/pypy-5.1.1-linux64/site-packages/twisted/internet/defer.py", line 306, in addCallbacks
    self._runCallbacks()
  File "/home/x/pypy-5.1.1-linux64/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/x/pypy-5.1.1-linux64/site-packages/autobahn/wamp/protocol.py", line 461, in <lambda>
    lambda _: txaio.as_future(self.onJoin, details),
  File "/home/x/pypy-5.1.1-linux64/site-packages/txaio/tx.py", line 408, in as_future
    return maybeDeferred(fun, *args, **kwargs)
--- <exception caught here> ---
  File "/home/x/pypy-5.1.1-linux64/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/x/pypy-5.1.1-linux64/site-packages/twisted/internet/defer.py", line 1273, in unwindGenerator
    "instead got %r" % (f, gen))
exceptions.TypeError: inlineCallbacks requires <function onJoin at 0x0000000001702f20> to produce a generator; instead got None

```

**Comment by oberstet** [comment]
as the err msg says: you need to return a generator
