### ISSUE TITLE
`WrappingWebSocketServerFactory` doesn't handle factories that return `None`.

### ISSUE THREAD

**Issue by tomprince** [crossbario/autobahn-python#700]
https://twistedmatrix.com/documents/current/api/twisted.internet.interfaces.IProtocolFactory.html#buildProtocol documents that `buildProtocol` can return `None`, but when I do that, I get

```
Traceback (most recent call last):                                                                                                                                                                                 
  File ".../lib/python2.7/site-packages/twisted/protocols/basic.py", line 571, in dataReceived                                                                                                                     
    why = self.lineReceived(line)                                                                                                                                                                                  
  File ".../lib/python2.7/site-packages/twisted/web/http.py", line 1692, in lineReceived                                                                                                                           
    self.allContentReceived()                                                                                                                                                                                      
  File ".../lib/python2.7/site-packages/twisted/web/http.py", line 1781, in allContentReceived                                                                                                                     
    req.requestReceived(command, path, version)                                                                                                                                                                    
  File ".../lib/python2.7/site-packages/twisted/web/http.py", line 768, in requestReceived                                                                                                                         
    self.process()                                                                                                                                                                                                 
--- <exception caught here> ---                                                                                                                                                                                    
  File ".../lib/python2.7/site-packages/twisted/web/server.py", line 183, in process                                                                                                                               
    self.render(resrc)                                                                                                                                                                                             
  File ".../lib/python2.7/site-packages/twisted/web/server.py", line 234, in render                                                                                                                                
    body = resrc.render(self)                                                                                                                                                                                      
  File ".../lib/python2.7/site-packages/autobahn/twisted/resource.py", line 121, in render                                                                                                                         
    protocol = self._factory.buildProtocol(request.transport.getPeer())                                                                                                                                            
  File ".../lib/python2.7/site-packages/autobahn/twisted/websocket.py", line 428, in buildProtocol                                                                                                                 
    proto._proto.transport = proto                                                                                                                                                                                 
exceptions.AttributeError: 'NoneType' object has no attribute 'transport' 
````

Incidentally, The last line in the traceback should probably be `proto._proto.makeConnection(transport)`.

**Comment by oberstet** [comment]
We probably should use `makeConnection` (and let handle firing `madeConnection` too):

```
(cpy2711_10) oberstet@thinkpad-t430s:~/scm/crossbario/autobahn-python$ find autobahn -name "*.py" -exec grep -Hi "\.transport = " {} \;
autobahn/asyncio/rawsocket.py:        self.transport = transport
autobahn/asyncio/rawsocket.py:        self.transport = None
autobahn/asyncio/websocket.py:        self.transport = transport
autobahn/asyncio/websocket.py:        self.transport = None
autobahn/twisted/resource.py:        transport, request.channel.transport = request.channel.transport, None
autobahn/twisted/test/test_protocol.py:        p.transport = t
autobahn/twisted/test/test_protocol.py:        self.proto.transport = StringTransport()
autobahn/twisted/test/test_rawsocket.py:        p.transport = t
autobahn/twisted/test/test_rawsocket.py:        sp.transport = st
autobahn/twisted/websocket.py:        proto._proto.transport = proto
autobahn/twisted/websocket.py:        proto._proto.transport = proto
autobahn/websocket/test/test_protocol.py:        p.transport = t
autobahn/websocket/test/test_protocol.py:        self.transport = t
autobahn/websocket/test/test_protocol.py:        p.transport = t
autobahn/websocket/test/test_protocol.py:        self.transport = t
autobahn/websocket/test/test_websocket.py:        proto.transport = MagicMock()
autobahn/websocket/test/test_websocket.py:            self.transport = MagicMock()
autobahn/websocket/test/test_websocket.py:            self.proto.transport = self.transport
autobahn/websocket/test/test_websocket.py:            self.transport = MagicMock()
autobahn/websocket/test/test_websocket.py:            self.proto.transport = self.transport
```
