### ISSUE TITLE
async/await websocket

### ISSUE THREAD

**Issue by deounix** [crossbario/autobahn-python#757]
I can't use async/await in onConnect function, but it's working with other functions like (onOpen, onMessage, onClose)

Example:

```

	async def test(self, x):
		return x * x

	async def onConnect(self, request):
		print("Connected.")
		res = await self.test(10)
		print(res)
```

Error : 

```
Exception in callback WebSocketAdapterProtocol._consume.<locals>.process(<Future finished result=None>) at C:\Python35\lib\site-packages\autobahn\asyncio\websocket.py:109
handle: <Handle WebSocketAdapterProtocol._consume.<locals>.process(<Future finished result=None>) at C:\Python35\lib\site-packages\autobahn\asyncio\websocket.py:109>
Traceback (most recent call last):
  File "C:\Python35\lib\asyncio\events.py", line 125, in _run
    self._callback(*self._args)
  File "C:\Python35\lib\site-packages\autobahn\asyncio\websocket.py", line 113, in process
    self._dataReceived(data)
  File "C:\Python35\lib\site-packages\autobahn\websocket\protocol.py", line 1183, in _dataReceived
    self.consumeData()
  File "C:\Python35\lib\site-packages\autobahn\websocket\protocol.py", line 1212, in consumeData
    self.processHandshake()
  File "C:\Python35\lib\site-packages\autobahn\websocket\protocol.py", line 2745, in processHandshake
    self._onConnect(request)
  File "C:\Python35\lib\site-packages\autobahn\asyncio\websocket.py", line 212, in _onConnect
    self.succeedHandshake(res)
  File "C:\Python35\lib\site-packages\autobahn\websocket\protocol.py", line 2787, in succeedHandshake
    raise Exception("protocol accepted must be from the list client sent or None")
Exception: protocol accepted must be from the list client sent or None
```

**Comment by meejah** [comment]
From inspecting the code, it appears this case is at least *intended* to be handled properly. So, needs some investigation / testing.

**Comment by meejah** [comment]
Can you post more details? I took the asyncio/echo example from the repository and changed `onConnect` similar to your code above but that worked for me. This is using Python 3.5 on Debian.

**Comment by meejah** [comment]
Ah! Okay, when I change the *server* similar to above, then it fails -- so this is only the server-side `onConnect`.

**Comment by deounix** [comment]
@meejah Yes. it's only with server-side.

In function (succeedHandshake) located in autobahn\websocket\potocol.py

```
    def succeedHandshake(self, res):
        """
        Callback after onConnect() returns successfully. Generates the response for the handshake.
        """
        protocol = None
        headers = {}
        if type(res) == tuple:
            if len(res) > 0:
                protocol = res[0]
            if len(res) > 1:
                headers = res[1]
        else:
            protocol = res

        if protocol is not None and not (protocol in self.websocket_protocols):
            raise Exception("protocol accepted must be from the list client sent or None")
```
When I don't use async/await : res == None
When I'm using async/await : res == <coroutine object Start.onConnect at 0x03C1ACC0>

So this error happend cuz res is not None.

**Comment by oberstet** [comment]
fixed via https://github.com/crossbario/autobahn-python/pull/759

**Comment by stan-sack** [comment]
Hey guys. You're not catching the exception if onConnect is a coroutine. It means that I am unable to deny a connection by raising a ConnectionDeny. It would be awesome is someone could fix this!
