### ISSUE TITLE
Client is unable to connect websocket server behind a nginx server.

### ISSUE THREAD

**Issue by anandakella** [crossbario/autobahn-python#775]
I see the following error message on server side whenever the client tries to connect to server using HTTPS. 

INFO:root:failing WebSocket opening handshake ('missing port in HTTP Host header 'wsbackend' and server runs on non-standard port 9000 (wss = False)')
INFO:webserver.websocketserver:WebSocket connection closed: connection was closed uncleanly (missing port in HTTP Host header 'wsbackend' and server runs on non-standard port 9000 (wss = False))
ERROR:asyncio:Exception in callback _SelectorTransport._call_connection_lost(None)
handle: <Handle _SelectorTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "/usr/lib64/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/lib64/python3.5/asyncio/selector_events.py", line 613, in _call_connection_lost
    self._protocol.connection_lost(exc)
  File "/home/wooters/.virtualenvs/websocket-py/lib/python3.5/site-packages/autobahn/asyncio/websocket.py", line 99, in connection_lost
    self._connectionLost(exc)
  File "/home/wooters/.virtualenvs/websocket-py/lib/python3.5/site-packages/autobahn/websocket/protocol.py", line 2299, in _connectionLost
    WebSocketProtocol._connectionLost(self, reason)
  File "/home/wooters/.virtualenvs/websocket-py/lib/python3.5/site-packages/autobahn/websocket/protocol.py", line 1002, in _connectionLost
    self._onClose(self.wasClean, WebSocketProtocol.CLOSE_STATUS_CODE_ABNORMAL_CLOSE, "connection was closed uncleanly (%s)" % self.wasNotCleanReason)
  File "/home/wooters/.virtualenvs/websocket-py/lib/python3.5/site-packages/autobahn/asyncio/websocket.py", line 174, in _onClose
    res = self.onClose(wasClean, code, reason)
  File "/home/wooters/cloud/webserver/webserver/websocketserver.py", line 99, in onClose
    self.factory.unRegister(self)
  File "/home/wooters/cloud/webserver/webserver/websocketserver.py", line 67, in unRegister
    self.clients.pop(client.peer)
KeyError: 'tcp:127.0.0.1:37652'

What could be the issue ?

**Comment by meejah** [comment]
Are you incorrectly setting the Host header? (`missing port in HTTP Host header 'wsbackend' and server runs on non-standard port 9000`) https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_set_header

**Comment by danielfaust** [comment]
I had the same issue, but my headers were correct. I'm leaving the solution here as a reference.

Adding `externalPort=80` to the `WebSocketServerFactory` constructor was the solution for me.

```factory = WebSocketServerFactory(u"ws://0.0.0.0:8080", externalPort=80)```

https://stackoverflow.com/a/49632140/277267
