### ISSUE TITLE
wamp/protocol.py, _swallow_error; self.log appears to be None

### ISSUE THREAD

**Issue by FirefighterBlu3** [crossbario/autobahn-python#781]
``` python
#[... an uncaught exception in my own code]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/autobahn/wamp/protocol.py", line 430, in _swallow_error
    self.onUserError(fail, msg)
  File "/usr/lib/python3.6/site-packages/autobahn/wamp/protocol.py", line 411, in onUserError
    self.log.error(
AttributeError: 'NoneType' object has no attribute 'error'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 126, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.6/site-packages/txaio/aio.py", line 392, in done
    errback(create_failure())
  File "/usr/lib/python3.6/site-packages/autobahn/wamp/protocol.py", line 624, in _error
    return self._swallow_error(e, errmsg)
  File "/usr/lib/python3.6/site-packages/autobahn/wamp/protocol.py", line 432, in _swallow_error
    self.log.error(
AttributeError: 'NoneType' object has no attribute 'error'
```

my object is created as:

``` python
from autobahn.asyncio.wamp   import ApplicationSession
from autobahn.asyncio.wamp   import ApplicationRunner

class _Component(ApplicationSession):
    log   = None
    _ldap = None
    cache = {}
    topic_subscribers = {}
    
    @asyncio.coroutine
    def meta_on_join(self, details, b):
        print('meta_on_join {}, details: {}'.format(b, details))
[...]

def make(config):
    return _Component(config)

if __name__ == '__main__':
[...]
    runner = ApplicationRunner(
        url=irl,
        realm="smvfd",
        extra={'authid':'provider', 'cfg':cfg})

    runner.run(make)
```

**Comment by meejah** [comment]
I think it's because you're overriding the "log" class-attribute that `ApplicationSession` uses https://github.com/crossbario/autobahn-python/blob/master/autobahn/twisted/wamp.py#L86

**Comment by oberstet** [comment]
@FirefighterBlu3 yeah, you are setting `log = None`, @meejah is right
