### ISSUE TITLE
websocket sendClose make AssertionError Exception

### ISSUE THREAD

**Issue by likebeta** [crossbario/autobahn-python#822]
I use websocket in Twisted.  If program run for a long time， When I call sendClose to close websocket， it may cause AssertionError Exception. It come across 2 times, 15days per time

```
----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mj/bin/lemon/framework/private/service.py", line 52, in start
    TaskManager.start_loop()
  File "/home/mj/bin/lemon/framework/entity/manager.py", line 69, in start_loop
    stackless.run()
  File "/usr/local/bin/pypy2-v5.4.1/lib_pypy/stackless.py", line 484, in run
    schedule()
  File "/usr/local/bin/pypy2-v5.4.1/lib_pypy/stackless.py", line 524, in schedule
    _scheduler_switch(curr, task)
  File "/usr/local/bin/pypy2-v5.4.1/lib_pypy/stackless.py", line 150, in _scheduler_switch
    next.switch()
  File "/usr/local/bin/pypy2-v5.4.1/lib_pypy/stackless.py", line 65, in switch
    current._frame.switch(to=self._frame)
  File "/usr/local/bin/pypy2-v5.4.1/lib_pypy/stackless.py", line 53, in run
    return func(*argl, **argd)
  File "/usr/local/bin/pypy2-v5.4.1/lib_pypy/stackless.py", line 415, in _func
    func(*argl, **argd)
  File "/home/mj/bin/lemon/lemon/tasklet/connect.py", line 190, in on_server_heart_beat
    connection.terminate_connection()
  File "/home/mj/bin/lemon/framework/core/protocol/ws/ws.py", line 89, in terminate_connection
    self.sendClose()
  File "/usr/local/bin/pypy2-v5.4.1/site-packages/autobahn/websocket/protocol.py", line 1963, in sendClose
    self.sendCloseFrame(code=code, reasonUtf8=reasonUtf8, isReply=False)
  File "/usr/local/bin/pypy2-v5.4.1/site-packages/autobahn/websocket/protocol.py", line 1930, in sendCloseFrame
    self.onCloseHandshakeTimeout,
  File "/usr/local/bin/pypy2-v5.4.1/site-packages/txaio/_common.py", line 62, in call_later
    self._notify_bucket, real_time,
  File "/usr/local/bin/pypy2-v5.4.1/site-packages/txaio/tx.py", line 438, in create_delayed_call
    return _get_loop().callLater(delay, fun, *args, **kwargs)
  File "/usr/local/bin/pypy2-v5.4.1/site-packages/twisted/internet/base.py", line 711, in callLater
    "%s is not greater than or equal to 0 seconds" % (_seconds,)
AssertionError: -1.50203704834e-05 is not greater than or equal to 0 seconds
----------------------------------------------------------------------------------------------------
```

**Comment by meejah** [comment]
What version of Autobahn are you using? This sounds like something fixed/changed by #642

**Comment by likebeta** [comment]
@meejah  hello， autobahn version is 0.16.1

**Comment by oberstet** [comment]
@likebeta pls try latest release https://pypi.python.org/pypi/autobahn/0.18.2

**Comment by likebeta** [comment]
@oberstet @meejah thank you very mush
