### ISSUE TITLE
Twisted Web WebSocket resource broken

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-python#839]
Maybe (again) fallout from tx/H2:

```
May 15 11:04:22 cb-eu1 crossbar[19943]: 2017-05-15T11:04:22+0000 [Router      19958] Unhandled Error
May 15 11:04:22 cb-eu1 crossbar[19943]: Traceback (most recent call last):
May 15 11:04:22 cb-eu1 crossbar[19943]:   File "/home/ubuntu/crossbar-pypy2-1/site-packages/twisted/web/_http2.py", line 170, in dataReceived
May 15 11:04:22 cb-eu1 crossbar[19943]:     self._requestEnded(event)
May 15 11:04:22 cb-eu1 crossbar[19943]:   File "/home/ubuntu/crossbar-pypy2-1/site-packages/twisted/web/_http2.py", line 446, in _requestEnded
May 15 11:04:22 cb-eu1 crossbar[19943]:     stream.requestComplete()
May 15 11:04:22 cb-eu1 crossbar[19943]:   File "/home/ubuntu/crossbar-pypy2-1/site-packages/twisted/web/_http2.py", line 941, in requestComplete
May 15 11:04:22 cb-eu1 crossbar[19943]:     self._request.requestReceived(self.command, self.path, b'HTTP/2')
May 15 11:04:22 cb-eu1 crossbar[19943]:   File "/home/ubuntu/crossbar-pypy2-1/site-packages/twisted/web/http.py", line 771, in requestReceived
May 15 11:04:22 cb-eu1 crossbar[19943]:     self.process()
May 15 11:04:22 cb-eu1 crossbar[19943]: --- <exception caught here> ---
May 15 11:04:22 cb-eu1 crossbar[19943]:   File "/home/ubuntu/crossbar-pypy2-1/site-packages/twisted/web/server.py", line 190, in process
May 15 11:04:22 cb-eu1 crossbar[19943]:     self.render(resrc)
May 15 11:04:22 cb-eu1 crossbar[19943]:   File "/home/ubuntu/crossbar-pypy2-1/site-packages/twisted/web/server.py", line 241, in render
May 15 11:04:22 cb-eu1 crossbar[19943]:     body = resrc.render(self)
May 15 11:04:22 cb-eu1 crossbar[19943]:   File "/home/ubuntu/crossbar-pypy2-1/site-packages/autobahn/twisted/resource.py", line 121, in render
May 15 11:04:22 cb-eu1 crossbar[19943]:     protocol = self._factory.buildProtocol(request.transport.getPeer())
May 15 11:04:22 cb-eu1 crossbar[19943]: exceptions.AttributeError: 'NoneType' object has no attribute 'getPeer'
```

**Comment by oberstet** [comment]
This is Twisted 17.1.0 btw

**Comment by meejah** [comment]
You get this on all requests? Or "plain Web" requests incorrectly destined for the websocket endpoints?

**Comment by meejah** [comment]
I've tried tls and non-tls endpoints in explicit and universal transports and can't repeat this with CPython. I confirmed I was doing HTTP/2 requests (at least on the TLS endpoints).

**Comment by meejah** [comment]
I also can't repeat on PyPy 5.8.0

**Comment by oberstet** [comment]
strange .. assume it was just me doing something wrong.

**Comment by Mineleague** [comment]
Same Issue, not sure why...

**Comment by Mineleague** [comment]
Mine is in reactor
