### ISSUE TITLE
run(component) - handling errors in mainLoop?

### ISSUE THREAD

**Issue by xiamike** [crossbario/autobahn-python#859]
Hey guys,

I'm running a component on Heroku and storing data streamed through wss.  

Everything works fine but an error is being thrown in the main loop and it's causing the server to restart every few seconds.  

Any ideas on how to debug or trade the source of the error?  

Thanks!

```
2017-06-21T02:56:44.417601+00:00 app[web.1]: [2017-06-21 02:56:44 +0000] [4] [CRITICAL] WORKER TIMEOUT (pid:9)
2017-06-21T02:56:44.417772+00:00 app[web.1]: [2017-06-21 02:56:44 +0000] [4] [CRITICAL] WORKER TIMEOUT (pid:10)
2017-06-21T02:56:44.418036+00:00 app[web.1]: 2017-06-21T02:56:44+0000 Unexpected error in main loop.
2017-06-21T02:56:44.418209+00:00 app[web.1]: 2017-06-21T02:56:44+0000 Unexpected error in main loop.
2017-06-21T02:56:44.418442+00:00 app[web.1]: 2017-06-21T02:56:44+0000 Unhandled Error
2017-06-21T02:56:44.418444+00:00 app[web.1]: Traceback (most recent call last):
2017-06-21T02:56:44.418445+00:00 app[web.1]:   File "/app/datastream/poloniex.py", line 64, in run_stream
2017-06-21T02:56:44.418446+00:00 app[web.1]:     run(polx_component)
2017-06-21T02:56:44.418447+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/autobahn/twisted/component.py", line 432, in run
2017-06-21T02:56:44.418448+00:00 app[web.1]:     react(component._run, (components, ))
2017-06-21T02:56:44.418449+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/twisted/internet/task.py", line 936, in react
2017-06-21T02:56:44.418449+00:00 app[web.1]:     _reactor.run()
2017-06-21T02:56:44.418450+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/twisted/internet/base.py", line 1243, in run
2017-06-21T02:56:44.418450+00:00 app[web.1]:     self.mainLoop()
2017-06-21T02:56:44.418451+00:00 app[web.1]: --- <exception caught here> ---
2017-06-21T02:56:44.418452+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/twisted/internet/base.py", line 1255, in mainLoop
2017-06-21T02:56:44.418452+00:00 app[web.1]:     self.doIteration(t)
2017-06-21T02:56:44.418453+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/twisted/internet/epollreactor.py", line 218, in doPoll
2017-06-21T02:56:44.418454+00:00 app[web.1]:     l = self._poller.poll(timeout, len(self._selectables))
2017-06-21T02:56:44.418455+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 192, in handle_abort
2017-06-21T02:56:44.418456+00:00 app[web.1]:     sys.exit(1)
2017-06-21T02:56:44.418460+00:00 app[web.1]: exceptions.SystemExit: 1
2017-06-21T02:56:44.418461+00:00 app[web.1]:
2017-06-21T02:56:44.418703+00:00 app[web.1]: 2017-06-21T02:56:44+0000 Unhandled Error
2017-06-21T02:56:44.418704+00:00 app[web.1]: Traceback (most recent call last):
2017-06-21T02:56:44.418705+00:00 app[web.1]:   File "/app/datastream/poloniex.py", line 64, in run_stream
2017-06-21T02:56:44.418706+00:00 app[web.1]:     run(component)
2017-06-21T02:56:44.418707+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/autobahn/twisted/component.py", line 432, in run
2017-06-21T02:56:44.418707+00:00 app[web.1]:     react(component._run, (components, ))
2017-06-21T02:56:44.418708+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/twisted/internet/task.py", line 936, in react
2017-06-21T02:56:44.418709+00:00 app[web.1]:     _reactor.run()
2017-06-21T02:56:44.418709+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/twisted/internet/base.py", line 1243, in run
2017-06-21T02:56:44.418710+00:00 app[web.1]:     self.mainLoop()
2017-06-21T02:56:44.418711+00:00 app[web.1]: --- <exception caught here> ---
2017-06-21T02:56:44.418711+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/twisted/internet/base.py", line 1255, in mainLoop
2017-06-21T02:56:44.418712+00:00 app[web.1]:     self.doIteration(t)
2017-06-21T02:56:44.418713+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/twisted/internet/epollreactor.py", line 218, in doPoll
2017-06-21T02:56:44.418713+00:00 app[web.1]:     l = self._poller.poll(timeout, len(self._selectables))
2017-06-21T02:56:44.418714+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 192, in handle_abort
2017-06-21T02:56:44.418715+00:00 app[web.1]:     sys.exit(1)
2017-06-21T02:56:44.418715+00:00 app[web.1]: exceptions.SystemExit: 1
```

**Comment by oberstet** [comment]
https://groups.google.com/forum/#!forum/autobahnws
