### ISSUE TITLE
TypeError when session is left

### ISSUE THREAD

**Issue by om26er** [crossbario/autobahn-python#903]
Below code throws TypeError when the program exits, apparently the fix is to close the event loop as discussed here: https://bugs.python.org/issue23548
```
import asyncio
import sys

from autobahn.asyncio.component import Component, run

component = Component(
    transports=[
        {
            "type": "rawsocket",
            "url": "ws://localhost/ws",
            "endpoint": {
                "type": "unix",
                "path": "/home/om26er/Documents/cb/.crossbar/crossbar.sock",
            },
            "serializer": "json",
        }
    ],
    realm=u"realm1"
)

@component.on_join
async def on_join(session, details):
    data = await session.call('com.example.rawsocket-cbor.run', command)
    print(data)
    session.leave()


if __name__ == "__main__":
    command = sys.argv[1]
    run([component])
```

The said error logs:
```
Exception ignored in: <bound method BaseEventLoop.__del__ of <_UnixSelectorEventLoop running=False closed=True debug=False>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/base_events.py", line 431, in __del__
  File "/usr/lib/python3.5/asyncio/unix_events.py", line 58, in close
  File "/usr/lib/python3.5/asyncio/unix_events.py", line 139, in remove_signal_handler
  File "/usr/lib/python3.5/signal.py", line 47, in signal
TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object
```

**Comment by om26er** [comment]
fixed by https://github.com/crossbario/autobahn-python/pull/904
