### ISSUE TITLE
component API reliance on twisted

### ISSUE THREAD

**Issue by singlecheeze** [crossbario/autobahn-python#907]
See #295 If twisted is not loaded/wanted, opt of asyncio instead, autobahn-python/autobahn/wamp/component.py relies on two twisted imports (is this intentional?):
```python
from twisted.python.failure import Failure
from twisted.internet.error import ReactorNotRunning
```
```python
    def all_done(arg):
        log.debug("All components ended; stopping reactor")
        if isinstance(arg, Failure):
            log.error("Something went wrong: {log_failure}", failure=arg)
        try:
            reactor.stop()
        except ReactorNotRunning:
            pass
```
```text
Traceback (most recent call last):
  File "/home/user/PycharmProjects/app/backend/main.py", line 4, in <module>
    from autobahn.asyncio.component import Component, run
  File "/usr/lib/python3.6/site-packages/autobahn/asyncio/component.py", line 49, in <module>
    from autobahn.wamp import component
  File "/usr/lib/python3.6/site-packages/autobahn/wamp/component.py", line 34, in <module>
    from twisted.python.failure import Failure
ModuleNotFoundError: No module named 'twisted.python'
```

**Comment by meejah** [comment]
Hmm, thanks -- yess any asyncio/twisted specific code should definitely only exist in e.g. `autobahn.twisted.component` (or the asyncio equivalent).

**Comment by om26er** [comment]
I was just hit by this while I was updating one of my apps from ApplicationSession to Component.

**Comment by om26er** [comment]
fixed by https://github.com/crossbario/autobahn-python/pull/930
