### ISSUE TITLE
cryptosign: reading private ssh key is broken

### ISSUE THREAD

**Issue by om26er** [crossbario/autobahn-python#932]
Using this [example](https://github.com/crossbario/crossbar-examples/blob/master/authentication/cryptosign/static/client_raw_key_aio.py) but replacing a call to `cryptosign.SigningKey.from_raw_key` with `cryptosign.SigningKey.from_ssh_key` (as I had my private ssh key as a text file) fails, as there is an apparent bug out there, I narrowed it down to a simple test case below.
```
>>> from autobahn.wamp.cryptosign import SigningKey
>>> SigningKey.from_ssh_key('/home/om26er/.ssh/id_ed25519')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/autobahn/wamp/cryptosign.py", line 561, in from_ssh_key
    keydata, comment = _read_ssh_ed25519_privkey(keydata)
  File "/usr/local/lib/python3.5/dist-packages/autobahn/wamp/cryptosign.py", line 244, in _read_ssh_ed25519_privkey
    raise Exception('invalid OpenSSH private key (padlen={}, actual_pad={}, expected_pad={})'.format(len(pad), pad, _makepad(len(pad))))
Exception: invalid OpenSSH private key (padlen=7, actual_pad=b'\x01\x02\x03\x04\x05\x06\x07', expected_pad=)
```
The hack was to comment out this [condition](https://github.com/crossbario/autobahn-python/blob/master/autobahn/wamp/cryptosign.py#L240). I believe we are making some assumptions there that may not be always correct.

**Comment by om26er** [comment]
@oberstet Do you think removing that code would be a solution for this ?

**Comment by oberstet** [comment]
certainly not. just leave it for now

**Comment by meejah** [comment]
How was the key created? (FWIW, the loading code seems to work fine as-is on a random ed25519 key I just tried on Debian).

**Comment by om26er** [comment]
> How was the key created? (FWIW, the loading code seems to work fine as-is on a random ed25519 key I just tried on Debian).

I only ran `ssh-keygen -t ed25519` -- Gave it another try, same issue.

**Comment by oberstet** [comment]
@om26er are you using SSH agent, or are you directly reading the private key (which, when passphrase protected won't work)

**Comment by om26er** [comment]
> @om26er are you using SSH agent, or are you directly reading the private key (which, when passphrase protected won't work)?

I am directly reading a private key that is **not** passphrase protected.

**Comment by oberstet** [comment]
ok, this was working (with Twisted at least) for me in the past ..

**Comment by sethrh** [comment]
The `autobahn.wamp.cryptosign._makepad` function doesn't work properly in Python 3.

`_makepad(6)` returns `'\x01\x02\x03\x04\x05\x06'` (a str) rather than `b'\x01\x02\x03\x04\x05\x06'` (bytes). The str/bytes type difference causes the `pad != _makepad(len(pad))` the statement to fail.

My workaround is to monkey patch it: 

```
import autobahn.wamp.cryptosign
def _makepad_py3(size):
    return bytes(range(1, size + 1))
autobahn.wamp.cryptosign._makepad = _makepad_py3
```

This solution unfortunately does not work in Python2. To make it compatible with both, you'd need to do something like this: 
```
def _makepad_py23(size): 
    ''.join([chr(x) for x in range(1, size + 1)]).encode('ascii')
```
(I would hope there is a cleaner-looking solution, but that seems to work.)

**Comment by oberstet** [comment]
fixed via https://github.com/crossbario/autobahn-python/pull/1543

test:

```
(cpy39_1) (base) oberstet@intel-nuci7:~/scm/crossbario/autobahn-python$ ssh-keygen -t ed25519 -f /tmp/id_ed25519
Generating public/private ed25519 key pair.
Enter passphrase (empty for no passphrase): 
Enter same passphrase again: 
Your identification has been saved in /tmp/id_ed25519
Your public key has been saved in /tmp/id_ed25519.pub
The key fingerprint is:
SHA256:6ce5TX9KqKZAtEVk31ktodyrfbG0OPM8iZHtLh1ox7w oberstet@intel-nuci7
The key's randomart image is:
+--[ED25519 256]--+
|       .+     oo |
|       o . o =. .|
|      . . . = .. |
|     . o .     . |
|      o S     Bo |
|     . . . . Oo*+|
|      . . + =+Oo=|
|       . ..= ==E.|
|        .oo . =*.|
+----[SHA256]-----+
(cpy39_1) (base) oberstet@intel-nuci7:~/scm/crossbario/autobahn-python$ python -c "from autobahn.wamp.cryptosign import SigningKey; SigningKey.from_ssh_key('/tmp/id_ed25519')"
(cpy39_1) (base) oberstet@intel-nuci7:~/scm/crossbario/autobahn-python$ make test_cryptosign
USE_ASYNCIO=1 trial autobahn.wamp.test.test_wamp_cryptosign
autobahn.wamp.test.test_wamp_cryptosign
  TestAuth
    test_authenticator ...                                                 [OK]
    test_testvectors ...                                                   [OK]
    test_valid ...                                                         [OK]
  TestKey
    test_key ...                                                           [OK]
    test_pad ...                                                           [OK]
    test_pubkey ...                                                        [OK]

-------------------------------------------------------------------------------
Ran 6 tests in 0.087s

PASSED (successes=6)
USE_TWISTED=1 trial autobahn.wamp.test.test_wamp_cryptosign
autobahn.wamp.test.test_wamp_cryptosign
  TestAuth
    test_authenticator ...                                                 [OK]
    test_testvectors ...                                                   [OK]
    test_valid ...                                                         [OK]
  TestKey
    test_key ...                                                           [OK]
    test_pad ...                                                           [OK]
    test_pubkey ...                                                        [OK]

-------------------------------------------------------------------------------
Ran 6 tests in 0.089s

PASSED (successes=6)
(cpy39_1) (base) oberstet@intel-nuci7:~/scm/crossbario/autobahn-python$ 
```
