### ISSUE TITLE
Capital Letters in Registered URIs

### ISSUE THREAD

**Issue by gruns** [crossbario/autobahn-python#939]
Capital letters are not allowed in registered URIs. For example, `@register('example.camelCaseFails')` fails:

```python
#!/usr/bin/env python3.6
# -*- coding: utf-8 -*-

from autobahn.wamp import register
from autobahn.twisted.wamp import ApplicationRunner, ApplicationSession

class Example(ApplicationSession):
    @register('example.snake_case_succeeds')
    def foo(self):
        pass

    @register('example.camelCaseFails')
    def blah(self):
        pass

ApplicationRunner(None, None).run(WampServices)
```

Raises

```
Traceback (most recent call last):
  File "./autobahn-register-camel-case.py", line 7, in <module>
    class Example(ApplicationSession):
  File "./autobahn-register-camel-case.py", line 12, in Example
    @register('warden.camelCaseFails')
  File "/usr/local/lib/python3.6/dist-packages/autobahn/wamp/uri.py", line 343, in decorate
    f._wampuris.append(Pattern(real_uri, Pattern.URI_TARGET_ENDPOINT, options))
  File "/usr/local/lib/python3.6/dist-packages/autobahn/wamp/uri.py", line 215, in __init__
    raise Exception("invalid URI")
Exception: invalid URI
```

Googling, the only related discussion I found was

https://groups.google.com/forum/#!topic/autobahnws/mkjF21Fb8ow

Why, by default, are capital letters (e.g. for camelCase) not allowed in registered URIs?

**Comment by oberstet** [comment]
> Why, by default, are capital letters (e.g. for camelCase) not allowed in registered URIs?

because AutobahnPython follows the WAMP spec and enforces strict URIs per default: http://wamp-proto.org/static/rfc/draft-oberstet-hybi-crossbar-wamp.html#rfc.section.5.1.1.2

I seem to remember there are some knobs to change the default behavior, allowing "loose URIs" (see above)

**Comment by gruns** [comment]
Thanks for chiming in.

Why does WAMP not permit capital letters in URIs, though? Every major programming language, like those used the various WAMP implementations http://wamp-proto.org/implementations/, allows capital letters in identifiers -- why doesn't WAMP?

The forced changed from `CamelCaseFunctions` to `camel_case_functions` is confusing and unintuitive, especially for RPC. Doubly so when the common code format for languages with WAMP implementations is camelCase (Javascript, Java, etc).

**Comment by oberstet** [comment]
> Why does WAMP not permit capital letters in URIs, though? 

whitespace, funny characters and capital letters don't add any gain, but only hassles.

**Comment by gruns** [comment]
> whitespace, funny characters and capital letters don't add any gain, but only hassles.

Whitespace and funny characters: no. Whitespace and funny characters aren't
valid identifier characters in mainstream programming languages (Python,
Javascript, Go, etc) and thus I agree and see little reason to allow them in
WAMP URIs.

But capital letters? Not only are capital letters valid identifier characters in
every single WAMP implementation language enumerated here:

  * http://wamp-proto.org/implementations/

But hell: in Erlang, identifiers *have* to start with a capital letter.

  http://erlang.org/doc/reference_manual/expressions.html#id80984

Thus, support for capital letters engenders an immediate, tangible gain: WAMP
URIs, e.g. exported RPC functions, no longer have to needlessly and confusingly
mangle camelCase identifiers and function names.

That's exactly the problem I ran headlong into. I have to confusingly register
this function

```python
async def constructClientPayloadOnConnect(self, conn):
   pass
```

under a different, snake_case name.

```python
@register('construct_client_payload_on_connect')
async def constructClientPayloadOnConnect(self, conn):
   pass
```

I had one function name. Now I have two. Because of this restriction, the number
of function identifiers every developers has to remember and reason about
doubles. And I'm clearly not the only one to be bitten by this:

  https://groups.google.com/forum/#!topic/autobahnws/mkjF21Fb8ow

So there's an immediately gain for the allowance of capital letters: camelCase
identifiers and functions aren't mangled.

WAMP should encourage consistent code. Unfortunately this restriction does the
opposite.

Let's fix it!

**Comment by gruns** [comment]
Little bump: poor, innocent camelCase functions still suffer needlessly at the hands of this restriction.

Let's fix it!

**Comment by oberstet** [comment]
Ok, I agree: this issue has been raised more than once - I am reopening this:

Autobahn does have 2 levels of URI checking (internally), but this should be:

* better documented
* also be usable for decorators

The 2 levels of URI checking are "strict" vs "loose" and the respective regular expressions are here: https://github.com/crossbario/autobahn-python/blob/master/autobahn/wamp/message.py#L72

```python
# strict URI check allowing empty URI components
_URI_PAT_STRICT_EMPTY = re.compile(r"^(([0-9a-z_]+\.)|\.)*([0-9a-z_]+)?$")

# loose URI check allowing empty URI components
_URI_PAT_LOOSE_EMPTY = re.compile(r"^(([^\s\.#]+\.)|\.)*([^\s\.#]+)?$")

# strict URI check disallowing empty URI components
_URI_PAT_STRICT_NON_EMPTY = re.compile(r"^([0-9a-z_]+\.)*([0-9a-z_]+)$")

# loose URI check disallowing empty URI components
_URI_PAT_LOOSE_NON_EMPTY = re.compile(r"^([^\s\.#]+\.)*([^\s\.#]+)$")

# strict URI check disallowing empty URI components in all but the last component
_URI_PAT_STRICT_LAST_EMPTY = re.compile(r"^([0-9a-z_]+\.)*([0-9a-z_]*)$")

# loose URI check disallowing empty URI components in all but the last component
_URI_PAT_LOOSE_LAST_EMPTY = re.compile(r"^([^\s\.#]+\.)*([^\s\.#]*)$")
```

There are 6 regular expression, because there are 2 levels (strict vs loose), and 3 types: plain/exact URI, wildcard URI pattern and prefix URI pattern.

**Comment by oberstet** [comment]
the other option would be to redefine the "strict" pattern:

* `[0-9a-z_]+` => `[0-9A-Za-z_]+`

I think this makes sense anyways, as we do allow a leading digit, which is _not_ a valid identifier in most programming languages.

so above would allow for:

* identifiers (as in most programming languages), in any case mixing
* complete numerical (digits) strings
* hex strings (lower and upper cased)

but it still doesn't allow for eg base64:

* `[^-A-Za-z0-9+/=]|=[^=]|={3,}$` or
* `^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$`

source: https://stackoverflow.com/questions/475074/regex-to-parse-or-validate-base64-data

---

actually, I think a better user experience could be:

* by _default_, use the "loose" patterns, which only exclude whitespace, `#` and `.` (URI parts can be anything matching `[^\s\.#]*`)
* let the use switch to "strict", and have that use a pattern that results in valid identifiers for most programming languages

**Comment by gruns** [comment]
> actually, I think a better user experience could be:
>
> - by default, use the "loose" patterns, which only exclude whitespace, # and
>   . (URI parts can be anything matching [^\s\.#]*)
>
> - let the use switch to "strict", and have that use a pattern that results in
>   valid identifiers for most programming languages

Sounds great.

This solves the original problem (support for CamelCase) and opens the door for
other URIs schemes, too (e.g. base64). If a user wants to use emojis in their
URIs, I see no reason to stop them.

How can I help implement this?

**Comment by guanzo** [comment]
+1. Having camelCased uri's would be nice.
