### ISSUE TITLE
ProtocolError: invalid role 'subscriber' in 'roles' in 'details' in WELCOME

### ISSUE THREAD

**Issue by se4rch3r** [crossbario/autobahn-python#943]
I tried for a very long time to sort it out and decided to ask for help. 

With autobahn-js is working with code like this:
```
con = new autobahn.Connection({url: surl, "realm": "realm1"})
con.onopen = function(session){
    session.subscribe('channel', console.log)
}
con.open()
```

Maybe I'm doing something wrong?

**Code:**
```
import ssl
import txaio

from autobahn.asyncio.wamp import ApplicationSession, ApplicationRunner


class WebSck(ApplicationSession):
    async def onJoin(self, details):
        # listening for the corresponding message from the "backend"
        # (any session that .publish()es to this topic).
        def onevent(msg):
            print("Got event: {}".format(msg))
        await self.subscribe(onevent, u'channel2')


if __name__ == '__main__':
    txaio.start_logging(level='debug')
    ssl_c = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
    ssl_c.load_verify_locations(cafile='certificates/io-cert.pem')

    runner = ApplicationRunner("wss://s1.devzone", "realm1", ssl=ssl_c,
                               extra={'openHandshakeTimeout': 15, 'closeHandshakeTimeout': 15})
    runner.run(WebSck)
```

**Debug:** 
```2018-02-03T03:35:43 
[('logOctets', False, 'WampWebSocketClientFactory'),
 ('logFrames', False, 'WampWebSocketClientFactory'),
 ('trackTimings', False, 'WampWebSocketClientFactory'),
 ('utf8validateIncoming', True, 'WampWebSocketClientFactory'),
 ('applyMask', True, 'WampWebSocketClientFactory'),
 ('maxFramePayloadSize', 1048576, 'WampWebSocketClientFactory'),
 ('maxMessagePayloadSize', 1048576, 'WampWebSocketClientFactory'),
 ('autoFragmentSize', 65536, 'WampWebSocketClientFactory'),
 ('failByDrop', False, 'WampWebSocketClientFactory'),
 ('echoCloseCodeReason', False, 'WampWebSocketClientFactory'),
 ('openHandshakeTimeout', 2.5, 'WampWebSocketClientFactory'),
 ('closeHandshakeTimeout', 1, 'WampWebSocketClientFactory'),
 ('tcpNoDelay', True, 'WampWebSocketClientFactory'),
 ('autoPingInterval', 10.0, 'WampWebSocketClientFactory'),
 ('autoPingTimeout', 5.0, 'WampWebSocketClientFactory'),
 ('autoPingSize', 4, 'WampWebSocketClientFactory'),
 ('version', 18, 'WampWebSocketClientFactory'),
 ('acceptMaskedServerFrames', False, 'WampWebSocketClientFactory'),
 ('maskClientFrames', True, 'WampWebSocketClientFactory'),
 ('serverConnectionDropTimeout', 1, 'WampWebSocketClientFactory'),
 ('perMessageCompressionOffers',
  [PerMessageDeflateOffer(accept_no_context_takeover = True, accept_max_window_bits = True, request_no_context_takeover = False, request_max_window_bits = 0)],
  'WampWebSocketClientFactory'),
 ('perMessageCompressionAccept',
  <function ApplicationRunner.run.<locals>.accept at 0x7f5de928de18>,
  'WampWebSocketClientFactory')]
2018-02-03T03:35:43 connection to tcp:172.10.2.1:443 established
2018-02-03T03:35:43 GET / HTTP/1.1
User-Agent: AutobahnPython/17.10.1
Host: s1.devzone:443
Upgrade: WebSocket
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
Sec-WebSocket-Key: JhajrAx... 16 bytes keys in base64
Sec-WebSocket-Protocol: wamp.2.json.batched,wamp.2.json
Sec-WebSocket-Extensions: permessage-deflate; client_no_context_takeover; client_max_window_bits
Sec-WebSocket-Version: 13


2018-02-03T03:35:43 received HTTP response:

b'HTTP/1.1 101 Switching Protocols\r\nServer: nginx/1.4.6 (Ubuntu)\r\nDate: Sat, 03 Feb 2018 01:35:43 GMT\r\nConnection: upgrade\r\nUpgrade: websocket\r\nSec-WebSocket-Accept: f0gMn..total 20 bytes..UsKfg=\r\nSec-WebSocket-Protocol: wamp.2.json\r\n\r\n'


2018-02-03T03:35:43 received HTTP status line in opening handshake : HTTP/1.1 101 Switching Protocols
2018-02-03T03:35:43 received HTTP headers in opening handshake : {'server': 'nginx/1.4.6 (Ubuntu)', 'date': 'Sat, 03 Feb 2018 01:35:43 GMT', 'connection': 'upgrade', 'upgrade': 'websocket', 'sec-websocket-accept': 'f0gMn..total 20 bytes..UsKfg=', 'sec-websocket-protocol': 'wamp.2.json'}
2018-02-03T03:35:43 openHandshakeTimeoutCall.cancel
...
```
**Received utf-8 encoded message here from server. JSON for ease of reading:**
```
[
  2,
  23809598250901,
  {
    "roles": {
      "subscriber": {
        "features": {
          "publisher_identification": true,
          "pattern_based_subscription": true,
          "subscription_revocation": true,
          "payload_transparency": true,
          "payload_encryption_cryptobox": true
        }
      },
      "publisher": {
        "features": {
          "publisher_identification": true,
          "subscriber_blackwhite_listing": true,
          "publisher_exclusion": true,
          "payload_transparency": true,
          "x_acknowledged_event_delivery": true,
          "payload_encryption_cryptobox": true
        }
      },
      "caller": {
        "features": {
          "caller_identification": true,
          "progressive_call_results": true,
          "payload_transparency": true,
          "payload_encryption_cryptobox": true
        }
      },
      "callee": {
        "features": {
          "caller_identification": true,
          "pattern_based_registration": true,
          "shared_registration": true,
          "progressive_call_results": true,
          "registration_revocation": true,
          "payload_transparency": true,
          "payload_encryption_cryptobox": true
        }
      },
      "broker": {
        "features": {
          "subscriber_blackwhite_listing": true,
          "publisher_exclusion": true,
          "subscriber_metaevents": true
        }
      }
    },
    "transport": {
      "type": "ratchet",
      "transport_address": "127.0.0.1",
      "headers": {
        "X-Real-IP": [
          "172.10.0.3"
        ],
        "Host": [
          "s1.devzone"
        ],
        "X-Forwarded-For": [
          "172.10.0.3"
        ],
        "Upgrade": [
          "WebSocket"
        ],
        "Connection": [
          "upgrade"
        ],
        "User-Agent": [
          "AutobahnPython/17.10.1"
        ],
        "Pragma": [
          "no-cache"
        ],
        "Cache-Control": [
          "no-cache"
        ],
        "Sec-WebSocket-Key": [
          "JhajrAx... 16 bytes keys in base64"
        ],
        "Sec-WebSocket-Protocol": [
          "wamp.2.json.batched",
          "wamp.2.json"
        ],
        "Sec-WebSocket-Extensions": [
          "permessage-deflate; client_no_context_takeover; client_max_window_bits"
        ],
        "Sec-WebSocket-Version": [
          "13"
        ],
        "Content-Length": [
          0
        ]
      },
      "url": "http://s1.devzone/",
      "query_params": [],
      "cookies": []
    }
  }
]
```
And error:
```
...
2018-02-03T03:35:43 Traceback (most recent call last):
  File "/home/user/PycharmProjects/moning/venv/lib/python3.6/site-packages/autobahn/wamp/websocket.py", line 88, in onMessage
    for msg in self._serializer.unserialize(payload, isBinary):
  File "/home/user/PycharmProjects/moning/venv/lib/python3.6/site-packages/autobahn/wamp/serializer.py", line 131, in unserialize
    msg = Klass.parse(raw_msg)
  File "/home/user/PycharmProjects/moning/venv/lib/python3.6/site-packages/autobahn/wamp/message.py", line 813, in parse
    raise ProtocolError("invalid role '{0}' in 'roles' in 'details' in WELCOME".format(role))
autobahn.wamp.exception.ProtocolError: invalid role 'subscriber' in 'roles' in 'details' in WELCOME

2018-02-03T03:35:43 Failing WAMP-over-WebSocket transport: code=1002, reason="WAMP Protocol Error (invalid role 'subscriber' in 'roles' in 'details' in WELCOME)"
2018-02-03T03:35:43 failing connection: 1002: WAMP Protocol Error (invalid role 'subscriber' in 'roles' in 'details' in WELCOME)
2018-02-03T03:35:43 Protocol violation: masked server-to-client frame
2018-02-03T03:35:43 failing connection: 1002: masked server-to-client frame
2018-02-03T03:35:43 dropping connection to peer tcp:172.10.2.1:443 with abort=False: None
2018-02-03T03:35:43 _connectionLost: None
2018-02-03T03:35:43 Auto ping/pong: canceling autoPingPendingCall upon lost connection
2018-02-03T03:35:43 WAMP-over-WebSocket transport lost: wasClean=False, code=1006, reason="connection was closed uncleanly (None)"
2018-02-03T03:35:43 skipping closing handshake timeout: WebSocket connection is already closed``` @ #

**Comment by oberstet** [comment]
First of all, +1 for providing all the details! Very good. So the issue here is this:

You are using Ratchet (or Thruway over Ratchet?) behind Nginx, and Ratchet announces ("Received utf-8 encoded message here from server.") roles it is _not_ supposed to announce, namely:

* subscriber, publisher, caller, callee

A WAMP _router_ must only announce "broker" and "dealer" (the router roles).

A WAMP _client_ must only announce "subscriber, publisher, caller, callee".

AutobahnPython detects the invalid roles (invalid roles for a WAMP router) and bails out.

IOW: this is a bug in Ratchet ..

**Comment by oberstet** [comment]
To convince yourself that the issue is not in Autobahn, you could also just quickly/temporarily try Crossbar.io ... without changing anything in your client code (because that looks fine!).

**Comment by se4rch3r** [comment]
I can not influence the architecture of that project. Maybe need disable detecting invalid roles? Because with autobahn-js it work nice

**Comment by oberstet** [comment]
Sorry, no, an invalid role is fatal - AutobahnJS needs to get stricter.

**Comment by MickeyHHC** [comment]
I have encountered same problem.
I have no way. please help me.
