### ISSUE TITLE
ProtocolError: invalid serialization of WAMP message

### ISSUE THREAD

**Issue by goldcode88** [crossbario/autobahn-python#957]
I'd like to send a string by wamp, like this: "¬4薚b". 
Payload is dumped to this:
 S'[70,9,{},[{"retcode":200,"data":[{"dev_id":"\\u00004\xe8\x97\x94\xe5\x90\x84"}]}]]'. 

Crossbar will produce failure. The detail is following: 
Traceback (most recent call last):
  File "/Users/erlang/anaconda/lib/python2.7/site-packages/autobahn/wamp/websocket.py", line 88, in onMessage
    for msg in self._serializer.unserialize(payload, isBinary):
  File "/Users/erlang/anaconda/lib/python2.7/site-packages/autobahn/wamp/serializer.py", line 106, in unserialize
    raise ProtocolError("invalid serialization of WAMP message ({0})".format(e))
ProtocolError: invalid serialization of WAMP message ('ascii' codec can't encode character u'\xcb' in position 1: ordinal not in range(128))

**Comment by oberstet** [comment]
you need to send (unicode) strings, not binaries
