### ISSUE TITLE
FreeBSD test_reject_pending Unicode issue

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-python#962]
From running the unit tests for Twisted on:

```console
cpy3_1) [oberstet@fbsd1 ~/scm/oberstet/autobahn-python]$ uname -a
FreeBSD fbsd1 11.1-RELEASE FreeBSD 11.1-RELEASE #0 r321309: Fri Jul 21 02:08:28 UTC 2017     root@releng2.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64
(cpy3_1) [oberstet@fbsd1 ~/scm/oberstet/autobahn-python]$ python -V
Python 3.6.4
```

there is a Unicode issue in `autobahn.wamp.test.test_protocol.TestClose.test_reject_pending`:

```console
2018-03-22T20:00:28+0100 --> autobahn.wamp.test.test_protocol.TestClose.test_reject_pending <--
autobahn.wamp.test.test_protocol
  TestClose
    test_reject_pending ... 2018-03-22T20:00:28+0100 session closed with reason None [()]
2018-03-22T20:00:28+0100 Cancelling 1 outstanding requests
                                            [ERROR]
                                            [ERROR]

===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/home/oberstet/cpy3_1/lib/python3.6/site-packages/twisted/logger/_observer.py", line 131, in __call__
    observer(event)
  File "/home/oberstet/cpy3_1/lib/python3.6/site-packages/twisted/logger/_legacy.py", line 93, in __call__
    self.legacyObserver(event)
  File "/home/oberstet/cpy3_1/lib/python3.6/site-packages/twisted/python/log.py", line 562, in emit
    util.untilConcludes(self.write, timeStr + " " + msgStr)
  File "/home/oberstet/cpy3_1/lib/python3.6/site-packages/twisted/python/util.py", line 815, in untilConcludes
    return f(*a, **kw)
builtins.UnicodeEncodeError: 'ascii' codec can't encode character '\u2603' in position 39: ordinal not in range(128)

autobahn.wamp.test.test_protocol.TestClose.test_reject_pending
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/home/oberstet/cpy3_1/lib/python3.6/site-packages/twisted/logger/_observer.py", line 131, in __call__
    observer(event)
  File "/home/oberstet/cpy3_1/lib/python3.6/site-packages/txaio/tx.py", line 320, in __call__
    self._file.write(msg)
builtins.UnicodeEncodeError: 'ascii' codec can't encode character '\u2603' in position 35: ordinal not in range(128)

autobahn.wamp.test.test_protocol.TestClose.test_reject_pending
-------------------------------------------------------------------------------
Ran 259 tests in 1.011s

FAILED (skips=22, errors=2, successes=236)
*** Error code 1

Stop.
make: stopped in /usr/home/oberstet/scm/oberstet/autobahn-python
(cpy3_1) [oberstet@fbsd1 ~/scm/oberstet/autobahn-python]$ uname -a
FreeBSD fbsd1 11.1-RELEASE FreeBSD 11.1-RELEASE #0 r321309: Fri Jul 21 02:08:28 UTC 2017     root@releng2.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64
(cpy3_1) [oberstet@fbsd1 ~/scm/oberstet/autobahn-python]$ python -V
Python 3.6.4
(cpy3_1) [oberstet@fbsd1 ~/scm/oberstet/autobahn-python]$ 
```

**Comment by oberstet** [comment]
Actually, this was due to a missing locale setting / utf8 console support. Here is what I did to fix:

Edit `/etc/login.conf` for

```
default:\
        ...
        :charset=UTF-8:\
        :lang=de_DE.UTF-8:
```

Then run

```console
sudo cap_mkdb /etc/login.conf
```

With that, all tests run green now: https://gist.github.com/oberstet/0ee3d53ffd56c8bd3fcf65548a7a0fa1
