### ISSUE TITLE
Asyncio: Imports from autobahn.asyncio.component require twisted.

### ISSUE THREAD

**Issue by rdebroiz** [crossbario/autobahn-python#973]
Minimal working example:
```python
from autobahn.asyncio.component import Component
```
Output:
```
Traceback (most recent call last):
  File "pouet.py", line 1, in <module>
    from autobahn.asyncio.component import Component
  File "/home/rdebroiz/.virtualenvs/****/lib/python3.6/site-packages/autobahn/asyncio/component.py", line 49, in <module>
    from autobahn.wamp import component
  File "/home/rdebroiz/.virtualenvs/****/lib/python3.6/site-packages/autobahn/wamp/component.py", line 34, in <module>
    from twisted.python.failure import Failure
ModuleNotFoundError: No module named 'twisted.python'

```

**Comment by rdebroiz** [comment]
Okay it has been fixed already, sorry about that.
